ALTER TABLE C000056 ADD CODPEDIDOPAI VARCHAR(20);

CREATE TABLE PEDIDO_ENTREGAS (
	CODIGO VARCHAR(20),
	CODORCAMENTO VARCHAR(20),
	CODPRODUTO VARCHAR(20),
	QTDE_ENTREGUE FLOAT,
	DATA_ENTREGA TIMESTAMP,
	OBS VARCHAR(100)
);
