/*LEO - TABELAS PARA MODULO RECEITUARIO AGRONOMICO*/
CREATE TABLE RAGRO_ART (
    RG_TECNICO      INTEGER,
    RG_ART          VARCHAR(30),
    RG_DATA         DATE,
    RG_NUMINICIAL   INTEGER,
    RG_PROXIMO      INTEGER,
    RG_QUANTMAXIMA  INTEGER
);
CREATE TABLE RAGRO_PROPRIEDADE (
    RP_CODIGO           INTEGER,
    RP_CLIENTE          VARCHAR(6),
    RP_NOMEPROPRIEDADE  VARCHAR(80),
    RP_ENDERECO         VARCHAR(80),
    RP_MUNICIPIO        VARCHAR(40),
    RP_AREA             NUMERIC(15,2),
    RP_CODMUNICIPIO     VARCHAR(20),
    RP_CODUF            VARCHAR(20)
);

CREATE TABLE RAGRO_RECEITA (
    RR_DATA_EMISSAO         DATE,
    RR_TECNICO              INTEGER,
    RR_ART                  VARCHAR(30),
    RR_RECEITA_NUMERO       INTEGER,
    RR_NOTA_NUMERO          VARCHAR(10),
    RR_NOTA_SERIE           VARCHAR(3),
    RR_NOTA_EMISSAO         DATE,
    RR_CLIENTE              VARCHAR(6),
    RR_PROPRIEDADE          INTEGER,
    RR_PRODUTO              VARCHAR(50),
    RR_CULTURA              VARCHAR(50),
    RR_DIAGNOSTICO          VARCHAR(100),
    RR_MODALIDADE           VARCHAR(100),
    RR_AREAASERTRATADA      NUMERIC(15,2),
    RR_DOSAGEM              NUMERIC(15,2),
    RR_QTDECALDA            NUMERIC(15,2),
    RR_APLICACOESQTDE       NUMERIC(15,2),
    RR_QUANTIDADE           INTEGER,
    RR_INTERVALO            INTEGER,
    RR_RECEITATEXTO         INTEGER,
    RR_INFADICIONAIS        VARCHAR(3000),
    RR_DOSAGEM_UN           VARCHAR(50),
    RR_EPOCA                VARCHAR(3000),
    RR_AREAASERTRATADA_UN   VARCHAR(50),
    RR_QUANTIDADE_UN        VARCHAR(50),
    RR_CULTURA2             VARCHAR(50),
    RR_DIAGNOSTICO2         VARCHAR(100),
    RR_PRODUTO2             VARCHAR(50),
    RR_DOSAGEM2             NUMERIC(15,2),
    RR_EPOCA2               VARCHAR(3000),
    RR_MODALIDADE2          VARCHAR(100),
    RR_AREAASERTRATADA2     NUMERIC(15,2),
    RR_QTDECALDA2           NUMERIC(15,2),
    RR_INTERVALO2           INTEGER,
    RR_CULTURA3             VARCHAR(50),
    RR_DIAGNOSTICO3         VARCHAR(100),
    RR_PRODUTO3             VARCHAR(50),
    RR_DOSAGEM3             NUMERIC(15,2),
    RR_EPOCA3               VARCHAR(3000),
    RR_MODALIDADE3          VARCHAR(100),
    RR_AREAASERTRATADA3     NUMERIC(15,2),
    RR_QTDECALDA3           NUMERIC(15,2),
    RR_INTERVALO3           INTEGER,
    RR_QUANTIDADE2          INTEGER,
    RR_QUANTIDADE3          INTEGER,
    RR_QUANTIDADE_UN2       VARCHAR(50),
    RR_QUANTIDADE_UN3       VARCHAR(50),
    RR_RECEITATEXTO2        INTEGER,
    RR_RECEITATEXTO3        INTEGER,
    RR_AREAASERTRATADA_UN2  VARCHAR(50),
    RR_AREAASERTRATADA_UN3  VARCHAR(50),
    RR_DOSAGEM_UN2          VARCHAR(50),
    RR_DOSAGEM_UN3          VARCHAR(50),
    RR_APLICACOESQTDE2      NUMERIC(15,2),
    RR_APLICACOESQTDE3      NUMERIC(15,2),
    RR_INFADICIONAIS2       VARCHAR(3000),
    RR_INFADICIONAIS3       VARCHAR(3000)
);
CREATE TABLE RAGRO_TECNICO (
    RT_CODIGO    INTEGER,
    RT_NOME      VARCHAR(80),
    RT_ENDERECO  VARCHAR(80),
    RT_BAIRRO    VARCHAR(30),
    RT_CEP       VARCHAR(10),
    RT_CIDADE    VARCHAR(40),
    RT_RG        VARCHAR(25),
    RT_CPF       VARCHAR(18),
    RT_CREA      VARCHAR(30),
    RT_TELEFONE  VARCHAR(20),
    RT_EMAIL     VARCHAR(200),
    RT_FORMACAO  VARCHAR(30),
    RT_UF        VARCHAR(2),
    RT_ARTATUAL  VARCHAR(30)
);
CREATE TABLE RAGRO_TEXTORECEITA (
    RX_CODIGO  INTEGER,
    RX_NOME    VARCHAR(50),
    RX_TEXTO   VARCHAR(3000)
);
ALTER TABLE C000004 ADD SEAPI INTEGER;
ALTER TABLE C000004 ADD CPF_RESPONSAVEL_SIGA VARCHAR(18);
ALTER TABLE C000025 ADD AGRO_UNIDADE_SIGA VARCHAR(50);