/*DOUGLAS - VER QUANDO FOI A ÚLTIMA E PENÚLTIMA SINCRONIZAÇÃO DOS PDVS COM A BASE.FDB*/
ALTER TABLE C000001 ADD SERVIDOR_ULTIMASINCRONIZACAO DATE;
ALTER TABLE C000001 ADD SERVIDOR_PENULTIMASINCRONIZACAO DATE;
UPDATE C000001 SET SERVIDOR_ULTIMASINCRONIZACAO = '01-JAN-1999', SERVIDOR_PENULTIMASINCRONIZACAO = '01-JAN-1999';