CREATE TABLE IBPT (
    CODIGO     INTEGER,
    EX         INTEGER,
    TABELA     INTEGER,
    DESCRICAO  VARCHAR(100) CHARACTER SET WIN1252,
    ALIQNAC    NUMERIC(15,2),
    ALIQIMP    NUMERIC(15,2)
);
