DROP TABLE CODIFICA_TEMP;

CREATE TABLE CODIFICA_INDEX (
	ID INTEGER NOT NULL,
	TABELA VARCHAR(100),
	CODIGO INTEGER,
	CONSTRAINT CODIFICA_INDEX_PK PRIMARY KEY (ID)
);

CREATE TABLE CODIFICA_CANCE (
	ID INTEGER NOT NULL,
	TABELA VARCHAR(100),
	CODIGO INTEGER,
	CONSTRAINT CODIFICA_CANCE_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE CODIFICA_INDEX_SEQUENCE;
CREATE SEQUENCE CODIFICA_CANCE_SEQUENCE;

SET TERM ~; 

CREATE OR ALTER TRIGGER CODIFICA_INDEX_AUTOINCREMENT FOR CODIFICA_INDEX
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
	NEW.ID = NEXT VALUE FOR CODIFICA_INDEX_SEQUENCE;
END~

CREATE OR ALTER TRIGGER CODIFICA_CANCE_AUTOINCREMENT FOR CODIFICA_CANCE
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
	NEW.ID = NEXT VALUE FOR CODIFICA_CANCE_SEQUENCE;
END~

SET TERM ;~