INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('BICOS1', 'Cadastro de Bicos', 1);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('BOMBAS', 'Cadastro de Bombas', 1);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('CADTAN', 'Cadastro de Tanques', 1);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('COMBUS', 'Combustiveis', 1);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('CREDIT', 'Creditos Lancados/Baixados',1);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('ENCERR', 'Encerrantes', 1);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('LANLMC', 'Lancamentos do LMC', 1);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('LIVROL', 'Livro de LMC', 1);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('ULT_LM', 'Cadastro de LMC', 1);