CREATE TABLE PERMISSOES (CODIGO INTEGER NOT NULL, NOME VARCHAR(100), DOCUMENTO VARCHAR(10), NUMERO VARCHAR(20));

ALTER TABLE PERMISSOES ADD CONSTRAINT PK_PERMISSOES PRIMARY KEY (CODIGO);

COMMENT ON TABLE PERMISSOES IS 'DEFINE QUEM TEM PERMISSAO PARA BAIXAR OU VISUALIZAR OS XML DA NOTA NO SEFAZ'












