ALTER TABLE C000001 ADD USA_INFRASHOP INTEGER DEFAULT 0;
UPDATE C000001 SET USA_INFRASHOP = '0';

ALTER TABLE C000007 ADD ORIGEM VARCHAR(20) DEFAULT 'MERCURIOS';

CREATE TABLE INFRASHOP_ULTIMA_SINCRONIZACAO(TABELA VARCHAR(20) NOT NULL, TIPO_MOVIMENTO VARCHAR(1) NOT NULL, DATA_HORA TIMESTAMP NOT NULL);
ALTER TABLE INFRASHOP_ULTIMA_SINCRONIZACAO ADD CONSTRAINT PK_INFRASHOP_ULTIMA_SINCRONIZAC PRIMARY KEY (TABELA, TIPO_MOVIMENTO);

CREATE TABLE INFRASHOP_DISTRIBUIDORA(COD_EMPRESA INTEGER NOT NULL, CNPJ VARCHAR(20) NOT NULL, PORTA INTEGER, AUTENTICACAO_USUARIO VARCHAR(100), AUTENTICACAO_SENHA VARCHAR(30), MIDDLEWARE_USUARIO VARCHAR(100), MIDDLEWARE_SENHA VARCHAR(30), EMPRESA_NOME VARCHAR(100));
ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD CONSTRAINT PK_INFRASHOP_DISTRIBUIDORA PRIMARY KEY (COD_EMPRESA);

ALTER TABLE C000025 ADD INFRASHOP_ENVIAR VARCHAR(1);
ALTER TABLE C000025 ADD INFRASHOP_ULTIMO_ENVIO TIMESTAMP;
ALTER TABLE C000025 ADD INFRASHOP_PENDENTE VARCHAR(1);
