CREATE TABLE ATUALIZACAO_ESTOQUE (
	CODIGO INTEGER NOT NULL,
	CODPRODUTO VARCHAR(20),
	CODBARRAS VARCHAR(20),
	PRODUTO VARCHAR(100),
	ESTOQUE_SISTEMA FLOAT,
	ESTOQUE_APP FLOAT,
	DIFERENCA FLOAT,
	"DATA" DATE,
	HORA TIME,
	DATA_MOVIMENTACAO TIMESTAMP
);
