ALTER TABLE CONSIGNADO_ITENS ADD CST VARCHAR(10);
ALTER TABLE CONSIGNADO_ITENS ADD SITUACAO_TRIBUTARIA VARCHAR(1);
ALTER TABLE CONSIGNADO_ITENS ADD ALIQUOTA NUMERIC(15,2);
ALTER TABLE CONSIGNADO_ITENS ADD MARGEM_AGREGADA NUMERIC(15,2);
ALTER TABLE CONSIGNADO_ITENS ADD CSOSN VARCHAR(60);
ALTER TABLE CONSIGNADO_ITENS ADD REDUCAO NUMERIC(15,2);
ALTER TABLE CONSIGNADO_ITENS ADD IPI NUMERIC(15,2);
ALTER TABLE CONSIGNADO_ITENS ADD PESO NUMERIC(15,3);
ALTER TABLE CONSIGNADO_ITENS ADD PESO_LIQUIDO NUMERIC(15,3);
ALTER TABLE CONSIGNADO_ITENS ADD NCM_CODIGO VARCHAR(20);

CREATE TABLE CONSIGNADO_NFEREFERENCIA(COD_CONSIGNADO INTEGER NOT NULL, COD_VENDEDOR VARCHAR(10) NOT NULL, NUMERO VARCHAR(10) NOT NULL, SERIE VARCHAR(10) NOT NULL, DATA DATE, ULTIMA_ALTERACAO DATE);
ALTER TABLE CONSIGNADO_NFEREFERENCIA ADD CONSTRAINT PK_CONSIGNADO_NFEREFERENCIA PRIMARY KEY (NUMERO,SERIE);
INSERT INTO APP_ULTIMA_ALTERACAO (TABELA, ULTIMA_ALTERACAO) VALUES ('CONSIGNADO_NFEREFERENCIA', (select current_timestamp from rdb$database));
CREATE trigger att_consignadoreferencia for consignado_nfereferencia active before insert or update position 0 AS begin UPDATE APP_ultima_alteracao SET ULTIMA_ALTERACAO = (select current_timestamp from rdb$database) WHERE TABELA = 'CONSIGNADO_NFEREFERENCIA'; if ((old.cod_consignado <> new.cod_consignado) or (old.cod_vendedor <> new.cod_vendedor) or (old.numero <> new.numero)) then begin UPDATE CONSIGNADO_NFEREFERENCIA SET ULTIMA_ALTERACAO = (select current_timestamp from rdb$database) WHERE (NUMERO = NEW.numero) AND (SERIE = NEW.serie); end end;
CREATE trigger exclusao_consignado_nfereferenc for consignado_nfereferencia active before delete position 0 AS begin INSERT INTO EXCLUSOES(TABELA, CODIGO, DATA_HORA, CODIGO_COMPOSTO) VALUES('CONSIGNADO_NFEREFERENCIA', OLD.numero, (select current_timestamp from rdb$database), OLD.serie); end;
ALTER TABLE AGENDA ADD USUARIO VARCHAR(6);