ALTER TABLE C000001 ADD EMAIL_USUARIO_CONTADOR VARCHAR(100);

COMMENT ON COLUMN C000001.EMAIL_USUARIO_CONTADOR IS 'Email do usuario para enviar as notas para o contador';

ALTER TABLE C000001 ADD SENHA_USUARIO_CONTADOR VARCHAR(50);

COMMENT ON COLUMN C000001.SENHA_USUARIO_CONTADOR IS 'Senha do usuario para enviar as notas para o contador';

ALTER TABLE C000061 ADD XML_ENVIADO VARCHAR(1) DEFAULT 'N' ;

COMMENT ON COLUMN C000061.XML_ENVIADO IS 'Verifica se o usuario tem XML pendentes a enviar';







