ALTER TABLE C000025 ADD AGRO_VOLUMEEMBALAGEM_SIGA INTEGER;
UPDATE C000025 SET AGRO_VOLUMEEMBALAGEM_SIGA = 0;
ALTER TABLE RAGRO_RECEITA ADD RR_VOLUMEEMBALAGEM_SIGA INTEGER;
ALTER TABLE RAGRO_RECEITA ADD RR_VOLUMEEMBALAGEM_SIGA2 INTEGER;
ALTER TABLE RAGRO_RECEITA ADD RR_VOLUMEEMBALAGEM_SIGA3 INTEGER;