/*alterando campo CODIGO da tabela IBPT pois está numérica e tem que ser varchar por conta de NCM começam com "0"*/
ALTER TABLE IBPT ADD CODIGO_TEMP VARCHAR(10);
UPDATE IBPT SET CODIGO_TEMP = CODIGO;
ALTER TABLE IBPT DROP CODIGO;
ALTER TABLE IBPT ADD CODIGO VARCHAR(10);
UPDATE IBPT SET CODIGO = CODIGO_TEMP;
ALTER TABLE IBPT DROP CODIGO_TEMP;