update RDB$FIELDS set
RDB$FIELD_LENGTH = 100,
RDB$CHARACTER_LENGTH = 100
where RDB$FIELD_NAME = 'RDB$4418';

update RDB$FIELDS set
RDB$FIELD_LENGTH = 100,
RDB$CHARACTER_LENGTH = 100
where RDB$FIELD_NAME = 'RDB$4419';