update RDB$FIELDS set
RDB$FIELD_LENGTH = 150,
RDB$CHARACTER_LENGTH = 150
where RDB$FIELD_NAME = 'RDB$5795'
;

INSERT INTO C000083 (CODIGO, SITUACAO)
                       VALUES ('002', 'TRIBUTAÇÃO MONOFÁSICA PRÓPRIA SOBRE COMBUSTÍVEIS')
                     ;

INSERT INTO C000083 (CODIGO, SITUACAO)
                       VALUES ('015', 'TRIBUTAÇÃO MONOFÁSICA PRÓPRIA SOBRE E COM RESPONS. PELA RETENÇÃO SOBRE COMBUS.')
                     ;

INSERT INTO C000083 (CODIGO, SITUACAO)
                       VALUES ('053', 'TRIBUTAÇÃO MONOFÁSICA PRÓPRIA SOBRE COMBUSTÍVEIS COM RECOLHIMENTO DIFERIDO')
                     ;

INSERT INTO C000083 (CODIGO, SITUACAO)
                       VALUES ('061', 'TRIBUTAÇÃO MONOFÁSICA PRÓPRIA SOBRE COMBUSTÍVEIS COBRADO ANTERIORMENTE')
                     ;