CREATE TABLE CODIFICA_TEMP (
	CODIGO INTEGER NOT NULL,
	TABELA VARCHAR(100) NOT NULL,
	CODIGO_TEMP VARCHAR(20) NOT NULL,
	TERMINAL VARCHAR(20) NOT NULL,
	IP VARCHAR(100) NOT NULL,
	NOME_COMPUTADOR VARCHAR(100) NOT NULL,
	DATAHORA TIMESTAMP NOT NULL,
	CONSTRAINT CODIFICA_TEMP_PK PRIMARY KEY (CODIGO)
);

ALTER TABLE C000032 ALTER NUMERONOTA TYPE VARCHAR(10);