ALTER TABLE BENEFICIO_FISCAL ADD DESCR_BENEFICIO_NFE VARCHAR(300);
ALTER TABLE BENEFICIO_FISCAL ADD CODPRODUTO VARCHAR(6);
ALTER TABLE C000062 ADD DESCR_BENEFICIO_NFE VARCHAR(300);
ALTER TABLE C000088 ADD CEST VARCHAR(10);
