SET TERM ^;

CREATE OR ALTER TRIGGER C000025_DEL FOR C000025 AFTER DELETE
AS
BEGIN
	INSERT INTO EXCLUSOES(TABELA, CODIGO, DATA_HORA) VALUES('C000025', old.codigo, current_TIMESTAMP);
	
	DELETE FROM C000100 C100 WHERE C100.CODPRODUTO = OLD.CODIGO; 
	DELETE FROM C000026 C26  WHERE C26.CODPRODUTO  = OLD.CODIGO;   

	IF ( (SELECT COUNT(*) FROM PENDENTE WHERE TABELA = 'C000025' AND COD_TABELA = OLD.CODIGO) = 0 ) THEN
        /*se nao estiver na tabela pendente, cadastra*/
        INSERT INTO PENDENTE(TABELA, COD_TABELA, ACAO, SERVIDORPDV, TRAYAPI)
        VALUES              ('C000025', OLD.CODIGO, 'DELETE', '', 0);
    ELSE
        /*se estiver na tabela pendente, atualiza*/
        UPDATE PENDENTE SET ACAO = 'DELETE', ServidorPDV = '', TrayAPI = 0
        WHERE TABELA = 'C000025' AND COD_TABELA = OLD.CODIGO;
END^

SET TERM ;^