ALTER TABLE C000007 ADD INFRASHOP_PENDENTE VARCHAR(1);
ALTER TABLE C000007 ADD INFRASHOP_ULTIMO_ENVIO TIMESTAMP;
UPDATE C000007 SET ORIGEM = 'MERCURIOS';
ALTER TABLE C000056 ADD INFRASHOP_CODIGO VARCHAR(15);
ALTER TABLE C000056 ADD INFRASHOP_STATUS VARCHAR(3);

update RDB$RELATION_FIELDS set RDB$NULL_FLAG = 1 where (RDB$FIELD_NAME = 'CODIGO') and (RDB$RELATION_NAME = 'C000057');
ALTER TABLE C000057 ADD CONSTRAINT PK_C000057 PRIMARY KEY (CODIGO);

update RDB$RELATION_FIELDS set RDB$NULL_FLAG = 1 where (RDB$FIELD_NAME = 'CODORCAMENTO') and (RDB$RELATION_NAME = 'C000060');
update RDB$RELATION_FIELDS set RDB$NULL_FLAG = 1 where (RDB$FIELD_NAME = 'PRESTACAO') and (RDB$RELATION_NAME = 'C000060');
ALTER TABLE C000060 ADD CONSTRAINT PK_C000060 PRIMARY KEY (CODORCAMENTO,PRESTACAO);

CREATE TABLE INFRASHOP_PEDIDO_LOG(CODIGO INTEGER NOT NULL, COD_PEDIDO VARCHAR(10) NOT NULL, DESCRICAO VARCHAR(60) NOT NULL, DATA_HORA TIMESTAMP NOT NULL);
ALTER TABLE INFRASHOP_PEDIDO_LOG ADD CONSTRAINT PK_INFRASHOP_PEDIDO_RASTREAMENT PRIMARY KEY (CODIGO);
CREATE SEQUENCE GEN_IS_PEDIDO_LOG;
ALTER SEQUENCE GEN_IS_PEDIDO_LOG RESTART WITH 1;

set term ~;
CREATE trigger is_ped_rast_autoincrement for INFRASHOP_PEDIDO_LOG
active before insert position 0
AS
begin
    new.CODIGO = gen_id(GEN_IS_PEDIDO_LOG, 1);
end~
set term ;~

CREATE TABLE INFRASHOP_PEDIDO_RASTREAMENTO (COD_PEDIDO VARCHAR(10) NOT NULL, TIPO VARCHAR(5) NOT NULL, CODIGO INTEGER NOT NULL, DESCRICAO VARCHAR(100), DATA TIMESTAMP, NFE_URL VARCHAR(250), PENDENTE VARCHAR(1), 
ULTIMO_ENVIO TIMESTAMP, COD_PEDIDO_INFRASHOP VARCHAR(30), ORDENACAO INTEGER);
ALTER TABLE INFRASHOP_PEDIDO_RASTREAMENTO ADD CONSTRAINT PK_INFRASHOP_PEDIDO_RAST PRIMARY KEY (COD_PEDIDO,TIPO,CODIGO);

CREATE TABLE INFRASHOP_PEDIDO_NFE (COD_PEDIDO VARCHAR(10) NOT NULL, CHAVE_ACESSO VARCHAR(100) NOT NULL, CNPJ VARCHAR(15), NUMERO VARCHAR(20), SERIE VARCHAR(255), DATA_EMISSAO DATE, RASTREIO_TRANSPORTADORA VARCHAR(255), COD_PEDIDO_INFRASHOP VARCHAR(30), COD_NFE VARCHAR(10));
ALTER TABLE INFRASHOP_PEDIDO_NFE ADD CONSTRAINT PK_INFRASHOP_PEDIDO_NFE PRIMARY KEY (COD_PEDIDO,CHAVE_ACESSO);

CREATE TABLE INFRASHOP_PEDIDO_ITENS (COD_PEDIDO VARCHAR(10) NOT NULL, SKU_PRODUTO VARCHAR(30) NOT NULL, QTDE INTEGER, VALOR_UNITARIO NUMERIC(15,2), KIT_ID VARCHAR(30), COD_PEDIDO_INFRASHOP VARCHAR(30), COD_NFE VARCHAR(10));
ALTER TABLE INFRASHOP_PEDIDO_ITENS ADD CONSTRAINT PK_INFRASHOP_PEDIDO_ITENS PRIMARY KEY (COD_PEDIDO,SKU_PRODUTO);

ALTER TABLE C000056 ADD INFRASHOP_RASTREAMENTO_TIPO VARCHAR(5);
