CREATE TABLE PROD_SIMILARES (
    CODIGO      VARCHAR(6) NOT NULL,
    CODPRODUTO  VARCHAR(6),
    PRODUTO     VARCHAR(6)
);
ALTER TABLE PROD_SIMILARES ADD CONSTRAINT PK_PROD_SIMILARES PRIMARY KEY (CODIGO);