SET TERM ~;

CREATE OR ALTER TRIGGER C000007_INS FOR C000007 AFTER INSERT
AS
BEGIN
	IF ( (SELECT ID FROM PENDENTE WHERE TABELA = 'C000007' AND COD_TABELA = NEW.CODIGO) IS NULL ) THEN
		
		/*se nao estiver na tabela pendente, cadastra*/
		IF ((SELECT COUNT(ID) FROM PENDENTE) = 0) THEN
			INSERT INTO PENDENTE(ID, TABELA, COD_TABELA, ACAO, ServidorPDV, TrayAPI)
			VALUES
			(1, 'C000007', NEW.CODIGO, 'INSERT', '', 0);
		ELSE
			INSERT INTO PENDENTE(ID, TABELA, COD_TABELA, ACAO, ServidorPDV, TrayAPI)
			VALUES
			((SELECT MAX(ID)+1 FROM PENDENTE), 'C000007', NEW.CODIGO, 'INSERT', '', 0);
	
	ELSE
		
		/*se estiver na tabela pendente, atualiza*/
		UPDATE PENDENTE SET ACAO = 'INSERT', ServidorPDV = '', TrayAPI = 0 WHERE TABELA = 'C000007' AND COD_TABELA = NEW.CODIGO;

END~

CREATE OR ALTER TRIGGER C000007_UPD FOR C000007 AFTER UPDATE
AS
BEGIN
	IF ( (SELECT ID FROM PENDENTE WHERE TABELA = 'C000007' AND COD_TABELA = NEW.CODIGO) IS NULL ) THEN
		
		/*se nao estiver na tabela pendente, cadastra*/
		IF ((SELECT COUNT(ID) FROM PENDENTE) = 0) THEN
			INSERT INTO PENDENTE(ID, TABELA, COD_TABELA, ACAO, ServidorPDV, TrayAPI)
			VALUES
			(1, 'C000007', NEW.CODIGO, 'UPDATE', '', 0);
		ELSE
			INSERT INTO PENDENTE(ID, TABELA, COD_TABELA, ACAO, ServidorPDV, TrayAPI)
			VALUES
			((SELECT MAX(ID)+1 FROM PENDENTE), 'C000007', NEW.CODIGO, 'UPDATE', '', 0);
	
	ELSE
		
		/*se estiver na tabela pendente, atualiza*/
		UPDATE PENDENTE SET ACAO = 'UPDATE', ServidorPDV = '', TrayAPI = 0 WHERE TABELA = 'C000007' AND COD_TABELA = NEW.CODIGO;

END~

CREATE OR ALTER TRIGGER C000007_DEL FOR C000007 AFTER DELETE
AS
BEGIN
	IF ( (SELECT ID FROM PENDENTE WHERE TABELA = 'C000007' AND COD_TABELA = OLD.CODIGO) IS NULL ) THEN
		
		/*se nao estiver na tabela pendente, cadastra*/
		IF ((SELECT COUNT(ID) FROM PENDENTE) = 0) THEN
			INSERT INTO PENDENTE(ID, TABELA, COD_TABELA, ACAO, ServidorPDV, TrayAPI)
			VALUES
			(1, 'C000007', OLD.CODIGO, 'DELETE', '', 0);
		ELSE
			INSERT INTO PENDENTE(ID, TABELA, COD_TABELA, ACAO, ServidorPDV, TrayAPI)
			VALUES
			((SELECT MAX(ID)+1 FROM PENDENTE), 'C000007', OLD.CODIGO, 'DELETE', '', 0);
	
	ELSE
		
		/*se estiver na tabela pendente, atualiza*/
		UPDATE PENDENTE SET ACAO = 'DELETE', ServidorPDV = '', TrayAPI = 0 WHERE TABELA = 'C000007' AND COD_TABELA = OLD.CODIGO;

END~

SET TERM ;~