/*CAMPO P/ FILTRAR AS NFCE E NFE DE CADA EMPRESA PARA ENVIAR AO ESCRITÓRIO*/
ALTER TABLE NFCE ADD EMITENTE_CPFCNPJ VARCHAR(20);
UPDATE NFCE SET EMITENTE_CPFCNPJ = (SELECT CNPJ FROM C000004);

ALTER TABLE C000032 ADD EMITENTE_CPFCNPJ VARCHAR(20);
UPDATE C000032 SET EMITENTE_CPFCNPJ = (SELECT CNPJ FROM C000004) WHERE (NOT FISCAL_ORIGEM IS NULL) AND (FISCAL_ORIGEM <> '');