CREATE TABLE ESTACAO_PENDENTE (
	CODIGO INTEGER NOT NULL,
	TABELA VARCHAR(100),
	CODIGO_TABELA VARCHAR(50),
	ACAO VARCHAR(30));

CREATE TABLE ESTACAO_SINCRONIZADO (
	CODIGO INTEGER NOT NULL,
	NOME_ESTACAO VARCHAR(100));

ALTER TABLE C000048 ALTER COLUMN FISCAL_CODIGO TYPE VARCHAR(15);
ALTER TABLE C000032 ALTER COLUMN FISCAL_CODIGO TYPE VARCHAR(15);
ALTER TABLE CUPOM_SINCRONIZADO ADD SERIE_CUPOM INTEGER;


