CREATE TABLE RESPONSAVEL_TECNICO_NFE (
    CODIGO              INTEGER NOT NULL,
    INFRESPTEC_CNPJ     VARCHAR(50),
    INFRESPTEC_CONTATO  VARCHAR(100),
    INFRESPTEC_EMAIL    VARCHAR(150),
    INFRESPTEC_FONE     VARCHAR(50)
);


ALTER TABLE RESPONSAVEL_TECNICO_NFE ADD CONSTRAINT PK_RESPONSAVEL_TECNICO_NFE PRIMARY KEY (CODIGO);
