CREATE TABLE VARIACAO_PRECO_VENDA (CODIGO VARCHAR(10) NOT NULL, NOME VARCHAR(30), ACRESCIMO FLOAT, DESCONTO FLOAT, DATA DATE);
ALTER TABLE VARIACAO_PRECO_VENDA ADD CONSTRAINT PK_VARIACAO_PRECO_VENDA PRIMARY KEY (CODIGO);
ALTER TABLE C000014 ADD NAO_ACEITAR_PAGAMENTO CHAR(1);
ALTER TABLE C000014 ADD VALOR_MINIMO FLOAT;
ALTER TABLE C000025 ADD VARIACAO_PRECO_VENDA VARCHAR(10);
insert into c000000 (codigo, tabela, sequencia) values ('VARPRE', 'VARIACAO DE PRECO', '1');