/*DOUGLAS - TABELA DE CREDITOS DO CLIENTE*/
CREATE TABLE CLIENTE_CREDITO (CODCLIENTE VARCHAR(6) NOT NULL, VALOR_CREDITO NUMERIC(15,3) NOT NULL, CLIENTE_NOME VARCHAR(50) NOT NULL, DESCRICAO VARCHAR(300));
alter table CLIENTE_CREDITO add constraint PK_CLIENTE_CREDITO_A primary key (CODCLIENTE);

/*DOUGLAS - TABELA DOS PRODUTOS DO CRÉDITO*/
CREATE TABLE CLIENTE_CREDITO_PRODUTO (CODIGO INTEGER NOT NULL, CODCLIENTE VARCHAR(6) NOT NULL, SITUACAO VARCHAR(1) NOT NULL, CODPRODUTO VARCHAR(6) NOT NULL, PRODUTO_NOME VARCHAR(56) NOT NULL, VALOR NUMERIC(15,3) NOT NULL, VALOR_RESTANTE NUMERIC(15,3) NOT NULL, VALOR_UNITARIO NUMERIC(7,3) NOT NULL, QTDE NUMERIC(7,3) NOT NULL, DATA_ULTIMAALTERACAO DATE NOT NULL);
alter table CLIENTE_CREDITO_PRODUTO add constraint PK_CLIENTE_CREDITO_PRODUTO_A primary key (CODIGO, CODCLIENTE);

/*DOUGLAS - MOVIMENTAÇÕES/HISTÓRICO DOS CRÉDITOS*/
CREATE TABLE CLIENTE_CREDITO_MOV (CODIGO INTEGER NOT NULL, CODCLIENTE VARCHAR(6) NOT NULL, PEDIDO VARCHAR(16), NFCE VARCHAR(16), NFE VARCHAR(16), VENDA_INTERNA VARCHAR(16) NOT NULL, CUPOM VARCHAR(16), VALOR NUMERIC(15,2), DADOS VARCHAR(500));
alter table CLIENTE_CREDITO_MOV add constraint PK_CLIENTE_CREDITO_MOV primary key (CODIGO);

