CREATE TABLE REMESSA (CODIGO INTEGER NOT NULL, STATUS VARCHAR(20) NOT NULL, COD_FUNCIONARIO VARCHAR(6), COD_NFE_RETORNO VARCHAR(6), OBSERVACAO VARCHAR(250));
alter table REMESSA add constraint PK_REMESSA primary key (CODIGO);
alter table REMESSA add constraint VENDEDOR foreign key (COD_FUNCIONARIO) references C000008(CODIGO);

CREATE TABLE REMESSA_NFE (CODIGO INTEGER NOT NULL, COD_REMESSA INTEGER NOT NULL, COD_TRANSPORTADOR VARCHAR(10), COD_NFE INTEGER, COD_CLIENTE INTEGER, DATA DATE NOT NULL);
alter table REMESSA_NFE add constraint PK_REMESSA_NFE primary key (CODIGO);
alter table REMESSA_NFE add constraint REMESSA foreign key (COD_REMESSA) references REMESSA(CODIGO);


CREATE TABLE REMESSA_NFE_ITEM (CODIGO INTEGER NOT NULL, COD_REMESSA_NFE INTEGER NOT NULL, COD_PRODUTO VARCHAR(6) NOT NULL, PRODUTO VARCHAR(150), QTDE_INICIAL NUMERIC(15,3) NOT NULL, QTDE_BONIFICACAO NUMERIC(15,3), QTDE_DEVOLUCAO NUMERIC(15,3), QTDE_VENDIDA NUMERIC(15,3), VALOR_UNITARIO NUMERIC(15,3));
ALTER TABLE REMESSA_NFE_ITEM ADD CONSTRAINT PK_REMESSA_NFE_ITEM PRIMARY KEY (CODIGO, COD_REMESSA_NFE);
alter table REMESSA_NFE_ITEM add constraint PRODUTO foreign key (COD_PRODUTO) references C000025(CODIGO);

CREATE TABLE BANCO_VENDEDOR_NOSSONUMERO (COD_CONTA VARCHAR(10) NOT NULL, COD_VENDEDOR VARCHAR(10) NOT NULL, NOSSONUMERO VARCHAR(10) NOT NULL, NOSSONUMERO_INICIO VARCHAR(10) NOT NULL, NOSSONUMERO_FIM VARCHAR(10) NOT NULL);

ALTER TABLE C000117 ADD NOSSONUMERO VARCHAR(10);
ALTER TABLE C000117 ADD BOLETO_MENSAGEM VARCHAR(400);
ALTER TABLE C000117 ADD BOLETO_INSTRUCOES_1 VARCHAR(80);
ALTER TABLE C000117 ADD BOLETO_INSTRUCOES_2 VARCHAR(80);
ALTER TABLE C000117 ADD BOLETO_INSTRUCOES_3 VARCHAR(80);
ALTER TABLE C000117 ADD VALOR_TAXABANCARIA NUMERIC(15,3);
ALTER TABLE C000117 ADD COD_CONTABANCARIA VARCHAR(10);

ALTER TABLE C000061 ADD COD_REMESSA VARCHAR(10);