SET TERM ^;

CREATE OR ALTER TRIGGER C000032_INS FOR C000032 BEFORE INSERT
AS
BEGIN
	IF ((NEW.PRECOCUSTO IS NULL) AND (NEW.CODPRODUTO IS NOT NULL)) THEN
		NEW.PRECOCUSTO = (SELECT C25.PRECOCUSTO FROM C000025 C25 WHERE C25.CODIGO = NEW.CODPRODUTO);
END^

SET TERM ;^