CREATE TABLE TRAY_VENDAS (
	ID INTEGER NOT NULL,
	PRODUCT_ID INTEGER,
	ORDER_ID INTEGER,
	QUANTITY INTEGER,
	VARIANT_ID INTEGER,
	PENDENTE SMALLINT,
	REFERENCE VARCHAR(100),
	PRICE FLOAT
);

ALTER TABLE C000018 ADD SINCRONIZA_TRAY INTEGER;