EXECUTE BLOCK
AS
BEGIN
  IF (NOT EXISTS(
    SELECT 1 FROM RDB$RELATIONS 
    WHERE RDB$RELATION_NAME = 'CCLASSTRIB'
  )) THEN
  BEGIN
    EXECUTE STATEMENT '
      CREATE TABLE CCLASSTRIB (
        CODIGO VARCHAR(6) NOT NULL,
        DESCRICAO VARCHAR(2000)
      )
    ';
  END
END;