ALTER TABLE TABELA_PRECOS ADD ULTIMA_ALTERACAO DATE;
ALTER TABLE PRODUTO_TABELA ADD ULTIMA_ALTERACAO DATE;
ALTER TABLE C000005 ADD ULTIMA_ALTERACAO DATE;
ALTER TABLE C000048 ADD DATA_CANCELAMENTO DATE;