/*DOUGLAS - IMPRESSÃO CLOUD CLARINDA - ETIQUETAS*/
ALTER TABLE C000001 DROP COMANDO_IMPRESSAO_ETIQUETA;

CREATE TABLE CLOUD_IMPRESSAO_ETIQUETA (CODIGO INTEGER NOT NULL, COMANDO VARCHAR(5000));
alter table CLOUD_IMPRESSAO_ETIQUETA add constraint PK_CLOUD_IMPRESSAO_ETIQUETA primary key (CODIGO);

/*ANDREI - TAMANHO DOS CAMPOS*/
ALTER TABLE FICHACLINICA
ALTER column VET1 TYPE VARCHAR(30);

ALTER TABLE FICHACLINICA
ALTER column VET2 TYPE VARCHAR(30);

ALTER TABLE FICHACLINICA
ALTER column CRMV2 TYPE VARCHAR(30);

ALTER TABLE FICHACLINICA
ALTER column FUNCIONARIO TYPE VARCHAR(30);

ALTER TABLE FICHACLINICA
ALTER column SETOR1 TYPE VARCHAR(30);

ALTER TABLE FICHACLINICA
ALTER column SETOR2 TYPE VARCHAR(30);

 ALTER TABLE FICHACLINICA
ALTER column RESPONSAVEL TYPE VARCHAR(30);


