ALTER TABLE INFRASHOP_TRADEMASTER_OPERATION ADD OPERATION_EXCEPTION BLOB SUB_TYPE 1 SEGMENT SIZE 32000;
ALTER TABLE INFRASHOP_TRADEMASTER_OPERATION ADD PENDENTE_ENVIO_OPERATION VARCHAR(1) DEFAULT 'N';