/*27-02-2018------CILANDRO-------*/


ALTER TABLE C000057 ADD COMISSAO_VENDEDOR NUMERIC(15,3);



CREATE TABLE PRODUTO_COMISSAO_VENDEDOR (
    CODIGO       VARCHAR(6),
    CODPRODUTO   VARCHAR(10),
    COMISSAO     NUMERIC(15,3),
    CODVENDEDOR  VARCHAR(6)
);

