SET TERM ^;

EXECUTE BLOCK AS
BEGIN
	IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS RF WHERE RF."RDB$RELATION_NAME" = 'INFRASHOP_DISTRIBUIDORA' AND RF."RDB$FIELD_NAME" = 'TRADEMASTER_USUARIO')) THEN
		EXECUTE STATEMENT 'ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD TRADEMASTER_USUARIO VARCHAR(30)';
END^

EXECUTE BLOCK AS
BEGIN
	IF (NOT EXISTS(SELECT 1 FROM RDB$RELATION_FIELDS RF WHERE RF."RDB$RELATION_NAME" = 'INFRASHOP_DISTRIBUIDORA' AND RF."RDB$FIELD_NAME" = 'TRADEMASTER_SENHA')) THEN
		EXECUTE STATEMENT 'ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD TRADEMASTER_SENHA VARCHAR(100)';
END^

SET TERM ;^