update RDB$FIELDS set
RDB$FIELD_LENGTH = 300,
RDB$CHARACTER_LENGTH = 300
where RDB$FIELD_NAME = 'RDB$4801';

update RDB$FIELDS set
RDB$FIELD_LENGTH = 302,
RDB$CHARACTER_LENGTH = 302
where RDB$FIELD_NAME = 'RDB$4763';




