SET TERM #;
EXECUTE block as
BEGIN
	if (not exists(select 1 from RDB$RELATION_FIELDS rf
				   where rf.RDB$RELATION_NAME = 'C000046' and rf.RDB$FIELD_NAME = 'CODCONTAREC'))
	then
		execute statement 'ALTER TABLE C000046 ADD CODCONTAREC INTEGER';
END#
SET TERM ;#
CREATE TABLE C000046P (CODCONTAREC VARCHAR(6), CODPRODUTO VARCHAR(13), PRODUTO VARCHAR(60), UNIDADE VARCHAR(5), QTDE NUMERIC(15,3), UNITARIO NUMERIC(15,3), TOTAL NUMERIC(15,3));