ALTER TABLE C000044 ADD DATAHORA TIMESTAMP;

SET TERM ~;

CREATE OR ALTER TRIGGER C000044_DATAHORA_INS FOR C000044
AFTER INSERT
as
begin
    UPDATE C000044 SET DATAHORA = (select current_timestamp FROM RDB$DATABASE) where codigo = new.codigo;
end~

SET TERM ;~