ALTER TABLE MDFE ADD NOME_PAGADOR VARCHAR(200);
ALTER TABLE MDFE ADD DOCUMENTO_PAGADOR VARCHAR(20);
ALTER TABLE MDFE ADD VALOR_TOTAL_CONTRATO NUMERIC(15,2) DEFAULT 0.00;
ALTER TABLE MDFE ADD FORMAPGTO VARCHAR(50);
ALTER TABLE MDFE ADD CONDPGTO INTEGER;
ALTER TABLE MDFE ADD CODBANCO VARCHAR(3);
ALTER TABLE MDFE ADD BANCO VARCHAR(100);
ALTER TABLE MDFE ADD AGENCIA VARCHAR(10);
ALTER TABLE MDFE ADD CHAVEPIX VARCHAR(50);
ALTER TABLE MDFE ADD CNPJ_IPEF VARCHAR(20);
ALTER TABLE MDFE ADD VALOR_ADIANTAMENTO NUMERIC(15,2) DEFAULT 0.00;
ALTER TABLE MDFE ADD VALOR_PARCELADO NUMERIC(15,2) DEFAULT 0.00;
ALTER TABLE MDFE ADD COMP_VALOR_VALE_PEDAGIO NUMERIC(15,2) DEFAULT 0.00;
ALTER TABLE MDFE ADD COMP_VALOR_DESPESAS NUMERIC(15,2) DEFAULT 0.00;
ALTER TABLE MDFE ADD COMP_VALOR_FRETE NUMERIC(15,2) DEFAULT 0.00;
ALTER TABLE MDFE ADD COMP_VALOR_IMPOSTOS NUMERIC(15,2) DEFAULT 0.00;
ALTER TABLE MDFE ADD COMP_VALOR_OUTROS NUMERIC(15,2) DEFAULT 0.00;
ALTER TABLE MDFE ADD COMP_OUTROS_DESCRICAO VARCHAR(200);
ALTER TABLE MDFE ADD QTDE_PARCELAS INTEGER;

CREATE TABLE MDFE_PARCELAS (
	CODIGO INTEGER NOT NULL,
	CODMDFE VARCHAR(6) NOT NULL,
	VENCIMENTO DATE NOT NULL,
	VALOR NUMERIC(15,2) NOT NULL,
	CONSTRAINT MDFE_PARCELAS_PK PRIMARY KEY (CODIGO)
);

CREATE SEQUENCE GEN_MDFE_PARCELAS_CODIGO;

SET TERM ^ ;
CREATE TRIGGER MFDE_PARCELAS_BI FOR MDFE_PARCELAS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.CODIGO IS NULL) THEN
        NEW.CODIGO = NEXT VALUE FOR GEN_MDFE_PARCELAS_CODIGO;
END ^
SET TERM ; ^

