/*AUMENTA A QTDE DE CARACTERES DO BAIRRO DE 30 PARA 60*/
update RDB$FIELDS set RDB$FIELD_LENGTH = 60, RDB$CHARACTER_LENGTH = 60 where RDB$FIELD_NAME = 'RDB$42';

/*AUMENTA A QTDE DE CARACTERES DO ENDEREÇO DE 50 PARA 100*/
update RDB$FIELDS set RDB$FIELD_LENGTH = 100, RDB$CHARACTER_LENGTH = 100 where RDB$FIELD_NAME = 'RDB$41';

/*AUMENTA A QTDE DE CARACTERES DO CIDADE DE 40 PARA 80*/
update RDB$FIELDS set RDB$FIELD_LENGTH = 80, RDB$CHARACTER_LENGTH = 80 where RDB$FIELD_NAME = 'RDB$43';