CREATE TABLE PAUTA_TERMOACORDO (CODIGO INTEGER, DESCRICAO VARCHAR(30), DATAINI DATE, DATAFIM DATE);
CREATE TABLE PAUTA_VALOR (CODIGO_TERMOACORDO INTEGER, PRODUTO VARCHAR(6), VALOR NUMERIC(15,3));
insert into c000000 (CODIGO,TABELA,SEQUENCIA) values ('PAUTA', ' PAUTA TERMO ACORDO','1');
ALTER TABLE C000056 ADD VENDA_SAZONAL VARCHAR(1);
ALTER TABLE C000056 ADD VENCIMENTO_SAZONAL VARCHAR(10);