ALTER TABLE C000009 ADD PAGA_COMISSAO CHAR(1);
ALTER TABLE C000009 ADD COMISSAO FLOAT;
UPDATE C000009 SET PAGA_COMISSAO = 'N';
UPDATE C000009 SET COMISSAO = 0;
CREATE GENERATOR GEN_GRUPO_COLABORADORES_ID;
CREATE TABLE GRUPO_COLABORADORES (CODIGO  INTEGER NOT NULL,  GRUPO   CHAR(20));
ALTER TABLE GRUPO_COLABORADORES ADD CONSTRAINT PK_GRUPO_COLABORADORES PRIMARY KEY (CODIGO);
SET TERM #;
CREATE OR ALTER TRIGGER GRUPO_COLABORADORES_BI FOR GRUPO_COLABORADORES ACTIVE BEFORE INSERT POSITION 0 as begin if (new.codigo is null) then new.codigo = gen_id(gen_grupo_colaboradores_id,1); end#
SET TERM ;#
ALTER TABLE C000008 ADD GRUPO_COLABORADORES INTEGER;
CREATE GENERATOR GEN_CLI_COMISSAO_FORNEC;
CREATE TABLE CLIENTE_COMISSAO_FORNECEDOR (CODIGO INTEGER NOT NULL, COD_CLIENTE VARCHAR(10), COD_FORNECEDOR VARCHAR(10), COMISSAO FLOAT);
ALTER TABLE CLIENTE_COMISSAO_FORNECEDOR ADD CONSTRAINT PK_CLIENTE_COMISSAO_FORNECEDOR PRIMARY KEY (CODIGO);
SET TERM #;
CREATE OR ALTER TRIGGER CLIENTE_COMISSAO_FORNECEDOR_BI FOR CLIENTE_COMISSAO_FORNECEDOR ACTIVE BEFORE INSERT POSITION 0 as begin if (new.codigo is null) then new.codigo = gen_id(gen_cli_comissao_fornec,1);end#
SET TERM ;#
