CREATE GENERATOR PIX_ID;

CREATE TABLE PIX_PIXAPAY (
    FMP_IDPK                     INTEGER,
    FMP_STATUS                   VARCHAR(50),
    FMP_PAGADOR_NOME             VARCHAR(50),
    FMP_PAGADOR_BANCO            VARCHAR(50),
    FMP_PAGADOR_CONTA            VARCHAR(50),
    FMP_PAGAMENTO_DATA           TIMESTAMP,
    FMP_PAGADOR_AGENCIA          VARCHAR(10),
    FMP_PAGADOR_DOCUMENTO        VARCHAR(50),
    FMP_PAGADOR_CONTA_TIPO       VARCHAR(10),
    FMP_COBRANCA_VALOR_RECEBIDO  DECIMAL(18,2),
    FMP_PAGAMENTO_TRANSACAO_ID   VARCHAR(100),
    NUMERO_CUPOM                 VARCHAR(50),
    VALOR_TOTAL                  DECIMAL(15,2),
    ID                           INTEGER NOT NULL
);

SET TERM ^ ;

CREATE OR ALTER TRIGGER PIX_AUTOINCREMENT FOR PIX_PIXAPAY
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    NEW.ID = NEXT VALUE FOR PIX_ID;
END^

SET TERM ; ^

ALTER TABLE PIX_PIXAPAY ADD CONSTRAINT PK_PIX_PIXAPAY PRIMARY KEY (ID);
ALTER TABLE C000048 	ADD MEIO_PIX DECIMAL(15,3);
ALTER TABLE L000003 	ADD VALOR40 NUMERIC(15,2);



