/*-consignado-*/
CREATE TABLE CONSIGNADO (CODIGO INTEGER NOT NULL, COD_CLIENTE VARCHAR(10) NOT NULL, DATA_INICIO DATE, SITUACAO CHAR(10) DEFAULT 'A', COD_VENDEDOR VARCHAR(10) NOT NULL, QTDE_TOTAL NUMERIC(15,2), VALOR_TOTAL NUMERIC(15,2), ULTIMA_ALTERACAO DATE);
ALTER TABLE CONSIGNADO ADD CONSTRAINT PK_CONSIGNADO PRIMARY KEY (CODIGO, COD_VENDEDOR);
CREATE trigger consignado_biu0 for consignado active before insert or update position 0 AS begin UPDATE APP_ultima_alteracao SET ULTIMA_ALTERACAO = (select current_timestamp from rdb$database) WHERE TABELA = 'CONSIGNADO'; end;
CREATE trigger consignado_exclusao for consignado active before delete position 0 AS begin INSERT INTO EXCLUSOES(TABELA, CODIGO, DATA_HORA, CODIGO_COMPOSTO) VALUES('CONSIGNADO', OLD.codigo, (select current_timestamp from rdb$database), OLD.cod_vendedor); end;

/*-consignado ITENS-*/
CREATE TABLE CONSIGNADO_ITENS (COD_CONSIGNADO INTEGER NOT NULL, COD_VENDEDOR VARCHAR(10) NOT NULL, CODIGO INTEGER NOT NULL, COD_PRODUTO VARCHAR(10) NOT NULL, COD_GRADE VARCHAR(10) NOT NULL, QTDE NUMERIC(15,2), VALOR_UNITARIO NUMERIC(15,2), VALOR_TOTAL NUMERIC(15,2), MOVIMENTO CHAR(10) DEFAULT 'S', DATA_MOVIMENTO DATE, ULTIMA_ALTERACAO DATE);
ALTER TABLE CONSIGNADO_ITENS ADD CONSTRAINT PK_CONSIGNADO_ITENS PRIMARY KEY (COD_CONSIGNADO, COD_VENDEDOR, CODIGO);
CREATE trigger consignado_itens for consignado_itens active before insert or update position 0 AS begin UPDATE APP_ultima_alteracao SET ULTIMA_ALTERACAO = (select current_timestamp from rdb$database) WHERE TABELA = 'CONSIGNADO_ITENS'; end;
CREATE trigger consignado_itens_bd0 for consignado_itens active before delete position 0 AS begin INSERT INTO EXCLUSOES (TABELA, CODIGO, DATA_HORA, CODIGO_COMPOSTO, CODIGO_COMPOSTO2) values('CONSIGNADO_ITENS', OLD.cod_consignado, (select current_timestamp from rdb$database), OLD.cod_vendedor, OLD.codigo); end;


ALTER TABLE C000007 ADD COD_CONSIGNADO INTEGER;
ALTER TABLE EXCLUSOES ADD CODIGO_COMPOSTO2 VARCHAR(10);
ALTER TABLE EXCLUSOES ADD CODIGO_COMPOSTO3 VARCHAR(10);
ALTER TABLE C000061 ADD CODFORNECEDOR VARCHAR(6);
ALTER TABLE C000062 ADD CODPRODUTOFORNECEDOR VARCHAR(20);
ALTER TABLE C000062 ADD ICMS_ALIQUOTA NUMERIC(15,2);
insert into c000000 (CODIGO, TABELA, SEQUENCIA) values('000117', 'Nota Fiscal - Parcelas', 0);
update c000000 set SEQUENCIA = (select MAX(CODIGO) FROM c000117) + 1 WHERE codigo = '000117';

ALTER TABLE C000009 ADD PEDIDO_MINIMO FLOAT DEFAULT 0;
UPDATE C000009 SET PEDIDO_MINIMO = 0;

CREATE TABLE TIPO_CLIENTE (CODIGO INTEGER NOT NULL, TIPO VARCHAR(30));
CREATE SEQUENCE GEN_TIPO_CLIENTE_ID;
create trigger tipo_cliente_bi for tipo_cliente active before insert position 0 as begin  if (new.codigo is null) then new.codigo = gen_id(gen_tipo_cliente_id,1); end;
ALTER TABLE C000007 ADD TIPO_CLIENTE INTEGER;

ALTER TABLE C000056 ADD REFERENCIA VARCHAR(10);