DROP TRIGGER C000007_INS;
DROP TRIGGER C000007_UPD;
DROP TRIGGER C000007_DEL;
DROP TRIGGER C000025_INS;
DROP TRIGGER C000025_UPD;
DROP TRIGGER C000025_DEL;

DELETE FROM ESTACAO_PENDENTE;
DELETE FROM ESTACAO_SINCRONIZADO;
DROP TABLE ESTACAO_PENDENTE;
DROP TABLE ESTACAO_SINCRONIZADO;

CREATE TABLE PENDENTE (
	ID INTEGER NOT NULL,
	TABELA VARCHAR(100),
	COD_TABELA VARCHAR(50),
	SERVIDORPDV VARCHAR(300),
	TRAYAPI INTEGER,
	ACAO VARCHAR(30)
);

ALTER TABLE PENDENTE
ADD CONSTRAINT PK_PENDENTE
PRIMARY KEY (ID);


