CREATE TABLE AGRUPAMENTO_NOTAS (AN_CODIGO INTEGER NOT NULL, AN_DESCRICAO VARCHAR(30));
alter table AGRUPAMENTO_NOTAS add constraint PK_AGRUPAMENTO_NOTAS primary key (AN_CODIGO);
ALTER TABLE C000087 ADD CODAGRUPAMENTO INTEGER;