CREATE TABLE PLANO_CONTAS_CONTABEIS (
    DT_ALT DATE,
    COD_NAT_CC VARCHAR(2),
    IND_CTA VARCHAR(1),
    NIVEL VARCHAR(5),
    COD_CTA VARCHAR(60),
    NOME_CTA VARCHAR(60));
ALTER TABLE CADBOMBA ADD TIPO_MEDICAO CHAR(1);
ALTER TABLE CADBOMBA ADD LACRE VARCHAR(20);
ALTER TABLE CADBOMBA ADD DATA DATE;
ALTER TABLE CADCOMBUSTIVEL ADD CODIGO_ANP VARCHAR(9);
ALTER TABLE CADCOMBUSTIVEL ADD CODIGO_PRODUTO VARCHAR(6);