CREATE TABLE PRODUTO_REFERENCIASFORNECEDORES (CODIGO VARCHAR(6) NOT NULL, CODPRODUTO VARCHAR(6), CODFORNECEDOR  VARCHAR(6), REFERENCIA VARCHAR(30), OBSERVACAO VARCHAR(50));
ALTER TABLE PRODUTO_REFERENCIASFORNECEDORES ADD CONSTRAINT PK_PRODUTO_REFERENCIASFORNECEDO PRIMARY KEY (CODIGO);
INSERT INTO C000000 (CODIGO, TABELA, SEQUENCIA) VALUES ('REFFOR', 'Referencias Fornecedores', 1);