ALTER TABLE REMESSA_NFE_ITEM ADD BASE_SUB NUMERIC(15,2);
ALTER TABLE REMESSA_NFE_ITEM ADD ICMS_SUB NUMERIC(15,2);
ALTER TABLE REMESSA_NFE_ITEM ADD IMPOSTOCA_VBCSTRET NUMERIC(15,2);
ALTER TABLE REMESSA_NFE_ITEM ADD IMPOSTOCA_VICMSSTRET NUMERIC(15,2);
ALTER TABLE REMESSA_NFE_ITEM ADD IMPOSTOCA_PST NUMERIC(15,2);