SET TERM ^;

CREATE OR ALTER TRIGGER C000049_UPD FOR C000049 AFTER UPDATE
AS
BEGIN
    IF ( (SELECT COUNT(*) FROM PENDENTE WHERE TABELA = 'C000007' AND COD_TABELA = NEW.CODCLIENTE) = 0 ) THEN
        INSERT INTO PENDENTE(TABELA, COD_TABELA, ACAO, SERVIDORPDV, TRAYAPI, MEEP)
        VALUES              ('C000007', NEW.CODCLIENTE, 'UPDATE', '', 0, '');
    ELSE
        UPDATE PENDENTE SET ACAO = 'UPDATE', ServidorPDV = '', TrayAPI = 0, MEEP = ''
        WHERE TABELA = 'C000007' AND COD_TABELA = NEW.CODCLIENTE;
END^

CREATE OR ALTER TRIGGER C000049_INS FOR C000049 AFTER INSERT
AS
BEGIN
    IF ( (SELECT COUNT(*) FROM PENDENTE WHERE TABELA = 'C000007' AND COD_TABELA = NEW.CODCLIENTE) = 0 ) THEN
        INSERT INTO PENDENTE(TABELA, COD_TABELA, ACAO, SERVIDORPDV, TRAYAPI, MEEP)
        VALUES              ('C000007', NEW.CODCLIENTE, 'INSERT', '', 0, '');
    ELSE
        UPDATE PENDENTE SET ACAO = 'INSERT', ServidorPDV = '', TrayAPI = 0, MEEP = ''
        WHERE TABELA = 'C000007' AND COD_TABELA = NEW.CODCLIENTE;
END^

SET TERM ;^
