ALTER TABLE C000083 ADD TIPO VARCHAR(2);
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('000', 'Tributação integral', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('010', 'Tributação com alíquotas uniformes', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('011', 'Tributação com alíquotas uniformes reduzidas', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('200', 'Alíquota reduzida', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('220', 'Alíquota fixa', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('221', 'Alíquota fixa proporcional', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('222', 'Redução de Base de Cálculo', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('400', 'Isenção', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('410', 'Imunidade e não incidência', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('510', 'Diferimento', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('515', 'Diferimento com redução de alíquota', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('550', 'Suspensão', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('620', 'Tributação Monofásica', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('800', 'Transferência de crédito', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('810', 'Ajuste de IBS na ZFM', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('811', 'Ajustes', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('820', 'Tributação em declaração de regime específico', 'rt');
INSERT INTO C000083 (CODIGO, SITUACAO, TIPO) VALUES ('830', 'Exclusão da Base de Cálculo', 'rt');