CREATE TABLE GRUPO_PRODUTO (GRUPO    VARCHAR(10) NOT NULL, PRODUTO  VARCHAR(10) NOT NULL);
ALTER TABLE GRUPO_PRODUTO ADD CONSTRAINT PK_GRUPO_PRODUTO PRIMARY KEY (GRUPO, PRODUTO);

CREATE TABLE FOTOS_PRODUTO (COD_PRODUTO INTEGER NOT NULL, COD_FOTO INTEGER NOT NULL, FOTO VARCHAR(100), DESCRICAO VARCHAR(50), ULTIMA_ALTERACAO DATE);
ALTER TABLE FOTOS_PRODUTO ADD CONSTRAINT PK_FOTOS_PRODUTO PRIMARY KEY (COD_PRODUTO, COD_FOTO);

ALTER TABLE C000008 ADD COD_GRUPO VARCHAR(10);

ALTER TABLE EXCLUSOES ADD CODIGO_COMPOSTO VARCHAR(10);
