CREATE TABLE ROMANEIO (
    CODIGO       VARCHAR(6) NOT NULL,
    DATAEMI       DATE,
    DATASAI       DATE,
    HORA          VARCHAR(5),
    CODVEICULO               VARCHAR(6),
    CODTRANSPORTADOR         VARCHAR(6),
    OBS           BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    TOTPESO       NUMERIC(15,3),
    TOTQTD        NUMERIC(15,3),
    TOTVLR        NUMERIC(15,3),
    TOTPED        INTEGER,
    IMPRESSO      CHAR(1)
);
alter table ROMANEIO add constraint PK_ROMANEIO primary key (CODIGO);
CREATE TABLE ROMANEIO_PED (
    CODROMANEIO   VARCHAR(6) NOT NULL,
    CODPEDIDO     VARCHAR(6) NOT NULL,
    CODCLIENTE    VARCHAR(6),
    VLRPEDIDO  NUMERIC(15,3),
    VOLUMES    NUMERIC(15,3),
    DATA       DATE
);
ALTER TABLE ROMANEIO_PED ADD CONSTRAINT PK_ROMANEIO_PED PRIMARY KEY (CODROMANEIO, CODPEDIDO);
CREATE TABLE ROMANEIO_ITENS (
    CODROMANEIO  VARCHAR(6) NOT NULL,
    CODPRODUTO   VARCHAR(6) NOT NULL,
    DESCRICAO   VARCHAR(60),
    UNIDADE     VARCHAR(6),
    QUANTIDADE  NUMERIC(15,3),
    TOTKG       NUMERIC(15,3),
    TOTVLR      NUMERIC(15,3),
    PRECOMED    NUMERIC(15,3)
);
ALTER TABLE ROMANEIO_ITENS ADD CONSTRAINT PK_ROMANEIO_ITENS PRIMARY KEY (CODROMANEIO, CODPRODUTO);
insert into c000000 (codigo, tabela, Sequencia) values ('romane', 'Romaneio de Carga', 1);