ALTER TABLE MDFE ADD SEG_RESPSEG VARCHAR(1);
UPDATE MDFE SET SEG_RESPSEG = '1';
ALTER TABLE MDFE ADD SEG_CNPJ VARCHAR(18);
ALTER TABLE MDFE ADD SEG_XSEG VARCHAR(30);
ALTER TABLE MDFE ADD SEG_NAPOL VARCHAR(20);
ALTER TABLE MDFE ADD SEG_NAVER VARCHAR(40);
ALTER TABLE MDFE ADD CIOT VARCHAR(20);