ALTER TABLE C000001 ADD BOLETO_TIPO_BOBINA INTEGER;
UPDATE C000001 SET BOLETO_TIPO_BOBINA = 0 WHERE BOLETO_TIPO_BOBINA IS NULL;

ALTER TABLE C000001 ADD CONTASRECEBER_TIPOPROTESTO VARCHAR(100);
UPDATE C000001 SET CONTASRECEBER_TIPOPROTESTO = 'Protestar dias úteis' WHERE CONTASRECEBER_TIPOPROTESTO IS NULL;
