ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD ENDPOINT_STOCK VARCHAR(250);
ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD ENDPOINT_PRICE VARCHAR(250);
ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD ENDPOINT_TRACKING VARCHAR(250);
ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD ENDPOINT_CUSTOMER VARCHAR(250);
ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD ENDPOINT_VOUCHER VARCHAR(250);
