ALTER TABLE C000001 ADD FORMACAO_PRECOS INTEGER;
ALTER TABLE C000001 ADD PEDIDO_WINDOWS INTEGER;
ALTER TABLE C000001 ADD USAR_LMC INTEGER;
UPDATE C000001 SET FORMACAO_PRECOS = 1;
UPDATE C000001 SET PEDIDO_WINDOWS = 0;

CREATE TABLE CADBICO (
    CODIGO       INTEGER NOT NULL,
    COD_PRODUTO  INTEGER,
    PRECO        NUMERIC(15,3),
    COD_BOMBA    INTEGER,
    ENCERRANTE   INTEGER,
    TANQUE       INTEGER);

ALTER TABLE CADBICO ADD CONSTRAINT PK_CADBICO PRIMARY KEY (CODIGO);

CREATE TABLE CADBOMBA (
    CODIGO            INTEGER NOT NULL,
    COD_PRODUTO       INTEGER,
    NOME_COMBUSTIVEL  VARCHAR(30),
    SERIE             VARCHAR(30),
    FABRICANTE        VARCHAR(30),
    MODELO            VARCHAR(30));

ALTER TABLE CADBOMBA ADD CONSTRAINT PK_CADBOMBA PRIMARY KEY (CODIGO);


CREATE TABLE CADCOMBUSTIVEL (
    NOME       VARCHAR(30),
    PR_COMPRA  NUMERIC(15,3),
    PR_CUSTO   NUMERIC(15,3),
    PR_VENDA   NUMERIC(15,3),
    CODIGO     INTEGER NOT NULL);

ALTER TABLE CADCOMBUSTIVEL ADD CONSTRAINT PK_CADCOMBUSTIVEL PRIMARY KEY (CODIGO);

CREATE TABLE CADTANQUE (
    CODIGO           INTEGER NOT NULL,
    COD_PRODUTO      INTEGER NOT NULL,
    CAP_MAXIMA       INTEGER NOT NULL,
    CAP_MINIMA       INTEGER,
    NUMERO_FISICO    INTEGER NOT NULL,
    ESTOQUE_INICIAL  NUMERIC(15,2),
    ESTOQUE_ATUAL    NUMERIC(15,2),
    ESTOQUE_MEDICAO  NUMERIC(15,2),
    VALOR_ENTRADA    NUMERIC(15,2),
    VALOR_SAIDA      NUMERIC(15,2),
    DATA_ULT_ENT     DATE,
    DATA_ULT_SAI     DATE,
    NUMERO_NF        VARCHAR(10));


ALTER TABLE CADTANQUE ADD CONSTRAINT PK_CADTANQUE PRIMARY KEY (CODIGO);


CREATE TABLE ENCERRANTES (
    CODIGO        INTEGER NOT NULL,
    DATA          DATE,
    COD_BICO      INTEGER,
    ABERTURA      INTEGER,
    ENCERRAMENTO  INTEGER,
    QUANTIDADE    NUMERIC(15,2),
    AFERICAO      NUMERIC(15,2),
    PRECO         NUMERIC(15,2),
    VALOR         NUMERIC(15,2),
    COD_PRODUTO   INTEGER,
    SITUACAO      CHAR(1));


ALTER TABLE ENCERRANTES ADD CONSTRAINT PK_ENCERRANTES PRIMARY KEY (CODIGO);

CREATE TABLE LMC (
    CODIGO            INTEGER NOT NULL,
    TANQUE            INTEGER,
    BOMBA             INTEGER,
    BICO              INTEGER,
    ABERTURA          INTEGER,
    ENCERRANTE        INTEGER,
    COMBUSTIVEL       INTEGER,
    DATA              DATE,
    PRECO             NUMERIC(15,3),
    QUANTIDADE        NUMERIC(15,3),
    TOTAL             NUMERIC(15,3),
    SITUACAO          INTEGER,
    NR_NOTA           INTEGER,
    NOTAFISCAL1       VARCHAR(10),
    NOTAFISCAL2       VARCHAR(10),
    NOTAFISCAL3       VARCHAR(10),
    NOTAFISCAL4       VARCHAR(10),
    QUANTNF1          INTEGER,
    QUANTNF2          INTEGER,
    QUANTNF3          INTEGER,
    QUANTNF4          INTEGER,
    BICO1             INTEGER,
    BICO2             INTEGER,
    BICO3             INTEGER,
    BICO4             INTEGER,
    BICO5             INTEGER,
    BICO6             INTEGER,
    BICO7             INTEGER,
    BICO8             INTEGER,
    ABER_BICO1        INTEGER,
    ABER_BICO2        INTEGER,
    ABER_BICO3        INTEGER,
    ABER_BICO4        INTEGER,
    ABER_BICO5        INTEGER,
    ABER_BICO6        INTEGER,
    ABER_BICO7        INTEGER,
    ABER_BICO8        INTEGER,
    ENC_BICO1         INTEGER,
    ENC_BICO2         INTEGER,
    ENC_BICO3         INTEGER,
    ENC_BICO4         INTEGER,
    ENC_BICO5         INTEGER,
    ENC_BICO6         INTEGER,
    ENC_BICO7         INTEGER,
    ENC_BICO8         INTEGER,
    AFER_BICO1        INTEGER,
    AFER_BICO2        INTEGER,
    AFER_BICO3        INTEGER,
    AFER_BICO4        INTEGER,
    AFER_BICO5        INTEGER,
    AFER_BICO6        INTEGER,
    AFER_BICO7        INTEGER,
    AFER_BICO8        INTEGER,
    QTEVEND_1         INTEGER,
    QTEVEND_2         INTEGER,
    QTEVEND_3         INTEGER,
    QTEVEND_4         INTEGER,
    QTEVEND_5         INTEGER,
    QTEVEND_6         INTEGER,
    QTEVEND_7         INTEGER,
    QTEVEND_8         INTEGER,
    TOTALVEND_1       NUMERIC(15,3),
    TOTALVEND_2       NUMERIC(15,3),
    TOTALVEND_3       NUMERIC(15,3),
    TOTALVEND_4       NUMERIC(15,3),
    TOTALVEND_5       NUMERIC(15,3),
    TOTALVEND_6       NUMERIC(15,3),
    TOTALVEND_7       NUMERIC(15,3),
    TOTALVEND_8       NUMERIC(15,3),
    ESTOQ_ABERTURA    INTEGER,
    ESTOQ_ESCRITURAL  INTEGER,
    ESTOQ_FECHAMENTO  INTEGER,
    PERDA_SOBRA       INTEGER,
    OBSERVACAO        VARCHAR(255),
    PAGINA            INTEGER);


ALTER TABLE LMC ADD CONSTRAINT PK_LMC PRIMARY KEY (CODIGO);

CREATE TABLE LMC_ABERFECH (
    CODIGO            INTEGER NOT NULL,
    COD_FILIAL        VARCHAR(6),
    FILIAL            VARCHAR(50),
    ENDERECO          VARCHAR(60),
    BAIRRO            VARCHAR(30),
    CEP               VARCHAR(9),
    CIDADE            VARCHAR(30),
    UF                VARCHAR(2),
    IE                VARCHAR(14),
    CNPJ              VARCHAR(25),
    IM                VARCHAR(20),
    DISTRIBUIDORA     VARCHAR(50),
    CAPACIDADE        INTEGER,
    COD_COMBUSTIVEL   INTEGER,
    NOME_COMBUSTIVEL  VARCHAR(30),
    NUMERO            VARCHAR(10),
    NUMERO_JUNTACOM   VARCHAR(10),
    DATA_ABERTURA     DATE,
    NUMERO_ORDEM      INTEGER,
    PAGINA_ATUAL      INTEGER);

ALTER TABLE LMC_ABERFECH ADD CONSTRAINT PK_LMC_ABERFECH PRIMARY KEY (CODIGO);

CREATE TABLE REG_1300 (
    CODIGO_ITEM     VARCHAR(10),
    DT_FECH         DATE,
    EST_ABERT       NUMERIC(15,3),
    VOL_ENTR        NUMERIC(15,3),
    VOL_DISP        NUMERIC(15,3),
    VOL_SAIDAS      NUMERIC(15,3),
    EST_ESC         NUMERIC(15,3),
    VAL_AJ_PERDA    NUMERIC(15,3),
    VAL_AJ_GANHO    NUMERIC(15,3),
    FECH_FISICO     NUMERIC(15,3),
    CODIGO_PRODUTO  VARCHAR(10),
    NUM_TANQUE      INTEGER,
    NUM_BICO1       INTEGER,
    NUM_BICO2       INTEGER,
    VAL_FECHA1      INTEGER,
    VAL_FECHA2      INTEGER,
    VAL_ABERT1      INTEGER,
    VAL_ABERT2      INTEGER,
    VOL_AFERI1      INTEGER,
    VOL_AFERI2      INTEGER,
    VOL_VENDAS1     INTEGER,
    VOL_VENDAS2     INTEGER);

CREATE TABLE REG_150 (
    NOME                VARCHAR(100),
    CNPJ                VARCHAR(14),
    CPF                 VARCHAR(11),
    IE                  VARCHAR(14),
    COD_MUNICIPIO_IBGE  VARCHAR(10),
    SUFRAMA             VARCHAR(9),
    ENDERECO            VARCHAR(60),
    NUMERO              VARCHAR(10),
    COMPLEMENTO         VARCHAR(60),
    BAIRRO              VARCHAR(60),
    CODIGO_PAR          CHAR(6),
    CODIGO              VARCHAR(8) NOT NULL);


ALTER TABLE REG_150 ADD PRIMARY KEY (CODIGO);


CREATE TABLE REG_190 (
    UNIDADE    VARCHAR(6),
    DESCRICAO  VARCHAR(10));

CREATE TABLE REG_200 (
    CODIGO         VARCHAR(10) NOT NULL,
    PRODUTO        VARCHAR(60),
    COD_BARRA      VARCHAR(13),
    UNIDADE        VARCHAR(6),
    NCM            VARCHAR(8),
    ALIQUOTA_ICMS  NUMERIC(15,2)
);


ALTER TABLE REG_200 ADD CONSTRAINT PK_REG_200 PRIMARY KEY (CODIGO);


CREATE TABLE ULT_ENCERRANTES (
    CODIGO        INTEGER NOT NULL,
    DATA          DATE,
    COD_BICO      INTEGER,
    ABERTURA      INTEGER,
    ENCERRAMENTO  INTEGER,
    QUANTIDADE    NUMERIC(15,2),
    AFERICAO      NUMERIC(15,2),
    PRECO         NUMERIC(15,2),
    VALOR         NUMERIC(15,2),
    COD_PRODUTO   INTEGER,
    SITUACAO      CHAR(1),
    ATUALIZADO    INTEGER);


CREATE TABLE ULT_LMC (
    CODIGO        INTEGER NOT NULL,
    DATA          DATE,
    COD_BICO      INTEGER,
    ABERTURA      INTEGER,
    ENCERRAMENTO  INTEGER,
    QUANTIDADE    NUMERIC(15,2),
    AFERICAO      NUMERIC(15,2),
    PRECO         NUMERIC(15,2),
    VALOR         NUMERIC(15,2),
    COD_PRODUTO   INTEGER,
    SITUACAO      CHAR(1),
    ATUALIZADO    INTEGER);

