/*DOUGLAS - GUARDAR CAMINHO DO XML DO EVENTO DE CANCELAMENTO DA NFC-E*/
ALTER TABLE NFCE ADD NFE_CANC_XML VARCHAR(240);


/*DOUGLAS - CRIAR CAMPO PARA SINCRONIZAR XML DAS NFCE DOS PDVS COM O SERVIDOR!*/
ALTER TABLE NFCE ADD XML_VENDA_COPIADO VARCHAR(1);
ALTER TABLE NFCE ADD XML_CANCELAMENTO_COPIADO VARCHAR(1);
UPDATE NFCE SET XML_VENDA_COPIADO = 'S', XML_CANCELAMENTO_COPIADO = 'S' WHERE (DATA < (SELECT current_timestamp FROM RDB$DATABASE) - 45);


