update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'RDB$3802' where (RDB$FIELD_NAME = 'VAL_FECHA1') and (RDB$RELATION_NAME = 'REG_1300');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'RDB$3802' where (RDB$FIELD_NAME = 'VAL_FECHA2') and (RDB$RELATION_NAME = 'REG_1300');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'RDB$3802' where (RDB$FIELD_NAME = 'VAL_ABERT1') and (RDB$RELATION_NAME = 'REG_1300');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'RDB$3802' where (RDB$FIELD_NAME = 'VAL_ABERT2') and (RDB$RELATION_NAME = 'REG_1300');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'RDB$3802' where (RDB$FIELD_NAME = 'VOL_AFERI1') and (RDB$RELATION_NAME = 'REG_1300');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'RDB$3802' where (RDB$FIELD_NAME = 'VOL_AFERI2') and (RDB$RELATION_NAME = 'REG_1300');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'RDB$3802' where (RDB$FIELD_NAME = 'VOL_VENDAS1') and (RDB$RELATION_NAME = 'REG_1300');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'RDB$3802' where (RDB$FIELD_NAME = 'VOL_VENDAS2') and (RDB$RELATION_NAME = 'REG_1300');