ALTER TABLE LMC_ABERFECH
ADD DATA_FECHAMENTO TIMESTAMP;

update RDB$FIELDS set
RDB$FIELD_TYPE = 37,
RDB$FIELD_LENGTH = 6,
RDB$CHARACTER_LENGTH = 6,
RDB$CHARACTER_SET_ID = 0,
RDB$COLLATION_ID = 0
where RDB$FIELD_NAME = 'RDB$3863';

ALTER TABLE LMC_ABERFECH
ADD REPRESENTANTE_EMPRESA VARCHAR(100);

ALTER TABLE LMC_ABERFECH
ADD REPRESENTANTE_CPF VARCHAR(15);

