ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD NOSSO_NUMERO VARCHAR(30) DEFAULT '0';
ALTER TABLE C000064 ADD INFRASHOP_COBRANCA_CODIGO INTEGER;

/*AUMENTAR O TAMANHO DO CAMPO NOSSONUMERO_PROXIMO*/
ALTER TABLE C000064 ADD NOSSONUMERO_PROXIMO_TEMP VARCHAR(15);
UPDATE C000064 SET NOSSONUMERO_PROXIMO_TEMP = NOSSONUMERO_PROXIMO;
ALTER TABLE C000064 DROP NOSSONUMERO_PROXIMO;
ALTER TABLE C000064 ADD NOSSONUMERO_PROXIMO VARCHAR(15);
UPDATE C000064 SET NOSSONUMERO_PROXIMO = NOSSONUMERO_PROXIMO_TEMP;
ALTER TABLE C000064 DROP NOSSONUMERO_PROXIMO_TEMP;

ALTER TABLE C000041 ADD INFRASHOP_COBRANCA_CODIGO INTEGER;
ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD TRADEMASTER_USUARIO VARCHAR(100);
ALTER TABLE INFRASHOP_DISTRIBUIDORA ADD TRADEMASTER_SENHA VARCHAR(30);