/*ATUALIZA A COLUNA CÓDIGO PARA NOT NULL*/
update RDB$RELATION_FIELDS set RDB$NULL_FLAG = 1 where (RDB$FIELD_NAME = 'CODIGO') and (RDB$RELATION_NAME = 'C000032');

ALTER TABLE C000032 DROP MOVIMENTO;
ALTER TABLE C000032 ADD MOVIMENTO VARCHAR(100);
UPDATE C000032 SET MOVIMENTO = MOVIMENTO_TEMP;
ALTER TABLE C000032 DROP MOVIMENTO_TEMP;

/*PRÓXIMO COMANDO PODE OCORRER ERRO EM CLIENTES QUE POSSUEM REGISTROS NA TABELA C000032 DUPLICADOS - FALAR COM DOUGLAS, SE NECESSÁRIO*/
ALTER TABLE C000032 ADD CONSTRAINT PK_C000032 PRIMARY KEY (CODIGO);

SET TERM ~;
CREATE OR ALTER trigger c000032_auto_increment for c000032
active before insert position 0
AS
    begin
        new.CODIGO = gen_id(GEN_C000032_ID, 1);
    end~
SET TERM ;~

SET TERM ~; 

EXECUTE block AS
	DECLARE VARIABLE x integer;
BEGIN
	SELECT MAX(CODIGO) + 1 FROM C000032 INTO X;
	EXECUTE STATEMENT 'ALTER SEQUENCE GEN_C000032_ID RESTART WITH ' || x;
END~

SET TERM ;~
