ALTER TABLE LOCACOES ADD LO_BLOQUEIOPROP DM_CHAR_LOGICO DEFAULT 'N';
UPDATE LOCACOES SET LO_BLOQUEIOPROP = 'N';
ALTER TABLE LOCACOES ADD LO_BLOQUEIOPROPMES DM_CHAR_MES;
ALTER TABLE LOCACOES ADD LO_BLOQUEIOLOC DM_CHAR_LOGICO DEFAULT 'N';
UPDATE LOCACOES SET LO_BLOQUEIOLOC = 'N';
ALTER TABLE LOCACOES ADD LO_BLOQUEIOLOCMES DM_CHAR_MES;
