ALTER TABLE CONFIGURACOES ADD CF_PORTALOLX DM_CHAR_LOGICO;
ALTER TABLE IMOVEIS ADD IM_PORTALOLX DM_CHAR_LOGICO;
UPDATE IMOVEIS SET IM_PORTALOLX = 'N';
UPDATE CONFIGURACOES SET CF_PORTALOLX = 'N';
ALTER TABLE CONFIGURACOES ADD CF_PORTALOLXEMAIL DM_VARCHAR_DESCRICAO;