ALTER TABLE USUARIO ADD US_OPARQMORTOIMOVEIS DM_CHAR_LOGICO DEFAULT 'S';
UPDATE USUARIO SET US_OPARQMORTOIMOVEIS = US_OPARQMORTO;
ALTER TABLE USUARIO ADD US_OPARQMORTOLOCACOES DM_CHAR_LOGICO DEFAULT 'S';
UPDATE USUARIO SET US_OPARQMORTOLOCACOES = US_OPARQMORTO;
ALTER TABLE USUARIO ADD US_OPARQMORTOINTERESSADOS DM_CHAR_LOGICO DEFAULT 'S';
UPDATE USUARIO SET US_OPARQMORTOINTERESSADOS = US_OPARQMORTO;

