/*DOUGLAS - CONTROLE DE ACESSO DE USUÁRIOS POR AGÊNCIA*/
/*DOUGLAS - NO CAMPO IN_AGENCIA TEM TODOS OS CÓDIGOS DE AGÊNCIAS SEPARADOS POR ; DO INTERESSADO, CONFORME NA TABELA INTERESSADOS_AGENCIA*/
ALTER TABLE USUARIO ADD US_AGENCIA VARCHAR(3);
ALTER TABLE USUARIO ADD US_GERENTE_AGENCIA DM_CHAR_LOGICO COLLATE PXW_INTL850;
ALTER TABLE INTERESSADOS ADD IN_AGENCIA VARCHAR(30);
CREATE TABLE INTERESSADOS_AGENCIA (IA_INTERESSADOS INTEGER NOT NULL, IA_AGENCIA INTEGER NOT NULL);
alter table INTERESSADOS_AGENCIA add constraint PK_INTERESSADOS_AGENCIA primary key (IA_INTERESSADOS,IA_AGENCIA);