ALTER TABLE NFSE_ITEM ADD CONSTRAINT FK_NFSE_ITEM_1 FOREIGN KEY (NFI_NFSECODIGO) REFERENCES NFSE(NF_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE NFSE_ITEM DROP CONSTRAINT FK_NFSE_ITEM_SERVICO;
ALTER TABLE NFSE_ITEM ADD CONSTRAINT FK_NFSE_ITEM_2 FOREIGN KEY (NFI_SERVICO) REFERENCES NFSESERVICO(NS_CODIGO) ON UPDATE CASCADE;
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_VARCHAR_10' where (RDB$FIELD_NAME = 'CI_CODIBGE') and (RDB$RELATION_NAME = 'CIDADES');