ALTER TABLE CONFIGURACOES ADD CF_RECLOCREPASSARMULTAPROP DM_CHAR_LOGICO DEFAULT 'N' COLLATE PXW_INTL850;
ALTER TABLE CONFIGURACOES ADD CF_RECLOCTIRARBONUS DM_CHAR_LOGICO DEFAULT 'N' COLLATE PXW_INTL850;
ALTER TABLE LOCACOES ADD LO_REPASSARMULTA DM_CHAR_LOGICO DEFAULT 'N' COLLATE PXW_INTL850;
UPDATE CONFIGURACOES SET CF_RECLOCREPASSARMULTAPROP = 'N';
UPDATE CONFIGURACOES SET CF_RECLOCTIRARBONUS = 'S';
UPDATE LOCACOES SET LO_REPASSARMULTA = 'N';