ALTER TABLE IMOVELNOVIDADES ADD IN_SEQUENCIAL DM_INTEGER_PK;

alter table IMOVELNOVIDADES drop constraint PK_IMOVELNOVIDADES;

alter table IMOVELNOVIDADES add constraint PK_IMOVELNOVIDADES primary key (IN_IMOVEL,IN_SEQUENCIAL) using index PK_IMOVELNOVIDADES;