ALTER TABLE CONFIGURACOES ALTER CF_COBRANCACECREDCEB 		TO CF_COBRANCAAILOSCEB;
ALTER TABLE CONFIGURACOES ALTER CF_COBRANCACECREDCONVENIO 	TO CF_COBRANCAAILOSCONVENIO;

ALTER TABLE CONFIGURACOES_COBRANCA ALTER CC_COBRANCACECREDCONVENIO 	TO CC_COBRANCAAILOSCONVENIO;
ALTER TABLE CONFIGURACOES_COBRANCA ALTER CC_COBRANCACECREDCEB		TO CC_COBRANCAAILOSCEB;