ALTER TABLE NFSECONFIGURACAO ADD NC_NATUREZAOPERACAO DM_VARCHAR_DESCRICAO;
ALTER TABLE NFSECONFIGURACAO ADD NC_REGIMEESPECIALTRIBUTACAO DM_VARCHAR_DESCRICAO;
ALTER TABLE NFSECONFIGURACAO ADD NC_OPTANTESIMPLESNACIONAL DM_CHAR_LOGICO;
ALTER TABLE NFSECONFIGURACAO ADD NC_INCENTIVADORCULTURAL DM_CHAR_LOGICO;
UPDATE NFSECONFIGURACAO SET NC_NATUREZAOPERACAO = 'TributacaoNoMunicipio';
UPDATE NFSECONFIGURACAO SET NC_REGIMEESPECIALTRIBUTACAO = 'MicroempresaMunicipal';
UPDATE NFSECONFIGURACAO SET NC_OPTANTESIMPLESNACIONAL = 'S';
UPDATE NFSECONFIGURACAO SET NC_INCENTIVADORCULTURAL = 'N';