ALTER TABLE LOCACOES ADD LO_ALUGUELSEMIPTU DM_CHAR_LOGICO;
ALTER TABLE LOCACOES ADD LO_ALUGUELSEMSEMSEGURO DM_CHAR_LOGICO;
UPDATE LOCACOES SET LO_ALUGUELSEMIPTU = 'N';
UPDATE LOCACOES SET LO_ALUGUELSEMSEMSEGURO = 'N';
