CREATE TABLE SUBTIPO (
    ST_CODIGO             DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    ST_TIPO               DM_CHAR_UNIDADE COLLATE PXW_INTL850 /* DM_CHAR_UNIDADE = CHAR(2) */,
    ST_DESCRICAO          DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    ST_DESCRICAORESUMIDA  DM_VARCHAR_10 COLLATE PXW_INTL850 /* DM_VARCHAR_10 = VARCHAR(10) */
);
ALTER TABLE SUBTIPO ADD CONSTRAINT PK_SUBTIPO PRIMARY KEY (ST_CODIGO);
ALTER TABLE IMOVEIS ADD IM_SUBTIPO DM_INTEGER;
alter table IMOVEIS add constraint FK_IMOVEIS_SUBTIPO foreign key (IM_SUBTIPO) references SUBTIPO(ST_CODIGO) on update CASCADE;
ALTER TABLE USUARIO ADD US_CAD_SUBTIPOIMOVEIS DM_CHAR_LOGICO DEFAULT 'S' COLLATE PXW_INTL850;
UPDATE USUARIO SET US_CAD_SUBTIPOIMOVEIS = 'S';