ALTER TABLE USUARIO ADD US_USUARIOECORRETOR DM_CHAR_LOGICO DEFAULT 'N';
ALTER TABLE USUARIO ADD US_CORRETOR DM_INTEGER;
ALTER TABLE USUARIO ADD CONSTRAINT FK_USUARIO_1 FOREIGN KEY (US_CORRETOR) REFERENCES CORRETOR(CO_CODIGO) ON UPDATE CASCADE;