/*DOUGLAS - RENOVACAO DAS INTEGRACOES E DE TABELAS NAO MAIS UTILIZADAS*/

DROP TABLE SERVERERROS;
DROP TABLE CONFIGURACOESSERVER;
CREATE TABLE ROBO_INTEGRACAO (DATA DATE NOT NULL, HORA VARCHAR(5) NOT NULL, INFO   VARCHAR(25), "LOG"  BLOB SUB_TYPE 1 SEGMENT SIZE 4096);
ALTER TABLE ROBO_INTEGRACAO ADD CONSTRAINT PK_ROBO_INTEGRACAO PRIMARY KEY (DATA, HORA);
GRANT SELECT ON MON$ATTACHMENTS TO PUBLIC;
GRANT SELECT ON MON$CALL_STACK TO PUBLIC;
GRANT SELECT ON MON$CONTEXT_VARIABLES TO PUBLIC;
GRANT SELECT ON MON$DATABASE TO PUBLIC;
GRANT SELECT ON MON$IO_STATS TO PUBLIC;
GRANT SELECT ON MON$MEMORY_USAGE TO PUBLIC;
GRANT SELECT ON MON$RECORD_STATS TO PUBLIC;
GRANT SELECT ON MON$STATEMENTS TO PUBLIC;
GRANT SELECT ON MON$TABLE_STATS TO PUBLIC;
GRANT SELECT ON MON$TRANSACTIONS TO PUBLIC;
ALTER TABLE CONFIGURACOES DROP CF_EMAILPARACOPIA;
DROP TABLE REMESSAOCORRENCIA;
ALTER TABLE CONFIGURACOES DROP CF_BOLETODIASBAIXA;