CREATE TABLE BONIFICACAO_HISTORICO (BH_CODIGO DM_INTEGER_PK NOT NULL, BH_LOCACAO DM_INTEGER, BH_LOCACAO_VALOR DM_DINHEIRO, BH_BONIFICACAO_VALOR DM_DINHEIRO, BH_BONIFICACAO_PORCENTAGEM DM_DINHEIRO, BH_MESINICIAL DM_VARCHAR_10, BH_QTDEMESES DM_INTEGER, BH_DATA DM_DATE, BH_DATAFIM DM_DATE, BH_DESCRICAO DM_VARCHAR_DESCRICAO);
alter table BONIFICACAO_HISTORICO add constraint PK_BONIFICACAO_HISTORICO primary key (BH_CODIGO);
alter table BONIFICACAO_HISTORICO add constraint FK_BONIFICACAO_HISTORICO_1 foreign key (BH_LOCACAO) references LOCACOES(LO_CODIGO) on update CASCADE;
ALTER TABLE LOCACOES ADD LO_BONIFICACAO_CODIGO DM_INTEGER;
ALTER TABLE LOCACOES ADD LO_BONIFICACAO_ULTIMAVERIF DM_CHAR_MES;
UPDATE LOCACOES SET LO_BONIFICACAO_CODIGO = '-1';
