ALTER TABLE CONFIGURACOES ADD CF_IMAGEMMARCADAGUA DM_VARCHAR_DESCRICAO COLLATE PXW_INTL850;

CREATE TABLE IMOVEISFOTOS (
    IF_IMOVEL            DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    IF_FOTO01            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO02            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO03            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO04            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO05            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO06            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO07            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO08            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO09            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO10            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    IF_FOTO01MARCADAGUA  DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO02MARCADAGUA  DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO03MARCADAGUA  DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO04MARCADAGUA  DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO05MARCADAGUA  DM_CHAR_LOGICO /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO06MARCADAGUA  DM_CHAR_LOGICO /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO07MARCADAGUA  DM_CHAR_LOGICO /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO08MARCADAGUA  DM_CHAR_LOGICO /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO09MARCADAGUA  DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */,
    IF_FOTO10MARCADAGUA  DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */
);

ALTER TABLE IMOVEISFOTOS ADD CONSTRAINT PK_IMOVEISFOTOS PRIMARY KEY (IF_IMOVEL);

ALTER TABLE IMOVEISFOTOS ADD CONSTRAINT FK_IMOVEISFOTOS_IMOVEIS FOREIGN KEY (IF_IMOVEL) REFERENCES IMOVEIS (IM_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE IMOVEIS ADD IM_ESTADO DM_CHAR_LOGICO COLLATE PXW_INTL850;

UPDATE IMOVEIS SET IM_ESTADO = 'D';

ALTER TABLE IMOVEIS ADD IM_ESTADOOCUPANTE DM_VARCHAR_MEDIO COLLATE PXW_INTL850;

ALTER TABLE IMOVEIS ADD IM_ESTADOENTREGA DM_VARCHAR_PEQUENO COLLATE PXW_INTL850;

ALTER TABLE CONTASRECEBER DROP CONSTRAINT FK_CONTASRECEBER_CLIENTE;

alter table CONTASRECEBER add constraint FK_CONTASRECEBER_CLIENTE foreign key (CR_CLIENTE) references CLIENTES(CL_CODIGO) on delete CASCADE on update CASCADE using index FK_CONTASRECEBER_CLIENTE;

ALTER TABLE CONTASRECEBER DROP CONSTRAINT FK_CONTASRECEBER_IMOVEL;

alter table CONTASRECEBER add constraint FK_CONTASRECEBER_IMOVEL foreign key (CR_IMOVEL) references IMOVEIS(IM_CODIGO) on delete CASCADE on update CASCADE using index FK_CONTASRECEBER_IMOVEL;
