ALTER TABLE CONFIGURACOES ADD CF_CAD_IMOVEL_FOTOOFERTA DM_CHAR_LOGICO COLLATE PXW_INTL850;
UPDATE CONFIGURACOES SET CF_CAD_IMOVEL_FOTOOFERTA = 'N';
ALTER TABLE CLIENTES ADD CL_CONJUGE_EMAIL DM_VARCHAR_DESCRICAO;
ALTER TABLE VENDALANCAMENTOS ADD VL_COMISSAO_IMOBILIARIA DM_CHAR_LOGICO;
ALTER TABLE VENDALANCAMENTOS ADD VL_IMOBILIARIA_CODLANCAMENTO DM_INTEGER;
ALTER TABLE VENDALANCAMENTOS ADD VL_IMOBILIARIA_VALOR DM_DINHEIRO;