ALTER TABLE ROBO_INTEGRACAO ADD TEMP VARCHAR(10);
UPDATE ROBO_INTEGRACAO SET TEMP = HORA || ':00';
ALTER TABLE ROBO_INTEGRACAO DROP CONSTRAINT PK_ROBO_INTEGRACAO;
ALTER TABLE ROBO_INTEGRACAO DROP HORA;
ALTER TABLE ROBO_INTEGRACAO ALTER TEMP TO HORA;
