CREATE TABLE IMOVELNOVIDADES (
    IN_IMOVEL     DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    IN_DATA       DM_DATE /* DM_DATE = DATE */,
    IN_DESCRICAO  DM_VARCHAR_DESCRICAO COLLATE PXW_INTL850 /* DM_VARCHAR_DESCRICAO = VARCHAR(100) */,
    IN_FUNCIONARIO   DM_VARCHAR_NOME COLLATE PXW_INTL850 /* DM_VARCHAR_NOME = VARCHAR(51) CHECK (VALUE<>'') */
);

ALTER TABLE IMOVELNOVIDADES ADD CONSTRAINT PK_IMOVELNOVIDADES PRIMARY KEY (IN_IMOVEL);

ALTER TABLE IMOVELNOVIDADES ADD CONSTRAINT FK_IMOVELNOVIDADES_IMOVEL FOREIGN KEY (IN_IMOVEL) REFERENCES IMOVEIS (IM_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;