ALTER TABLE IMOVEIS ADD IM_VALORVENDAALTDATA DM_DATE;
ALTER TABLE IMOVEIS ADD IM_VALORLOCACAOALTDATA DM_DATE;

CREATE TABLE IMOVEISALTVALOR (
    IA_IMOVEL     DM_INTEGER,
    IA_DATA       DM_DATE,
    IA_LOCVENDA   DM_CHAR_LOGICO,
    IA_VALORANT   DM_DINHEIRO,
    IA_VALORNOVO  DM_DINHEIRO,
    IA_USUARIO    DM_VARCHAR_10,
    IA_MOTIVO     DM_VARCHAR_MEDIO);

ALTER TABLE IMOVEISALTVALOR ADD CONSTRAINT FK_IMOVEISALTVALOR_1 FOREIGN KEY (IA_IMOVEL) REFERENCES IMOVEIS (IM_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;