ALTER TABLE CONFIGURACOES ADD CF_FOTOSREDIMENSIONAR DM_CHAR_LOGICO COLLATE PXW_INTL850;

ALTER TABLE CONFIGURACOES ADD CF_FOTOSMARCADAGUA DM_CHAR_LOGICO COLLATE PXW_INTL850;

ALTER TABLE CONFIGURACOES ADD CF_FOTOSOPCOES DM_CHAR_LOGICO COLLATE PXW_INTL850;

ALTER TABLE CONFIGURACOES ADD CF_FOTOSLARGURA DM_INTEGER;

ALTER TABLE CONFIGURACOES ADD CF_FOTOSALTURA DM_INTEGER;

UPDATE CONFIGURACOES SET CF_FOTOSREDIMENSIONAR = 'S';

UPDATE CONFIGURACOES SET CF_FOTOSMARCADAGUA = 'S';

UPDATE CONFIGURACOES SET CF_FOTOSOPCOES = 'S';

UPDATE CONFIGURACOES SET CF_FOTOSLARGURA = 640;

UPDATE CONFIGURACOES SET CF_FOTOSALTURA = 480;