ALTER TABLE EMPREEND ADD EM_INSCRIMOB1 DM_VARCHAR_MEDIO;
ALTER TABLE EMPREEND ADD EM_INSCRIMOB2 DM_VARCHAR_MEDIO;
ALTER TABLE EMPREEND ADD EM_INSCRIMOB3 DM_VARCHAR_MEDIO;
ALTER TABLE EMPREEND ADD EM_ELEVADOR DM_CHAR_LOGICO;
ALTER TABLE EMPREEND ADD EM_IMEDIACOES DM_VARCHAR_DESCRICAO;
ALTER TABLE EMPREEND ADD EM_OBS DM_VARCHAR_OBS_250;