ALTER TABLE USUARIO ADD US_CADNFSE DM_CHAR_LOGICO DEFAULT 'S';
UPDATE USUARIO SET US_CADNFSE = 'S';
ALTER TABLE USUARIO ADD US_CADNFSESERVICOS DM_CHAR_LOGICO DEFAULT 'S';
UPDATE USUARIO SET US_CADNFSESERVICOS= 'S';