ALTER TABLE AGENCIA ADD AC_RAZAOIMOB DM_VARCHAR_NOME;
ALTER TABLE AGENCIA ADD AC_CNPJ DM_CHAR_CNPJ;
ALTER TABLE AGENCIA ADD AC_CPFRESP DM_CHAR_CPF;
ALTER TABLE AGENCIA ADD AC_ENDERECOIMOB DM_VARCHAR_NOME;
ALTER TABLE AGENCIA ADD AC_BAIRROIMOB DM_VARCHAR_NOME;
ALTER TABLE AGENCIA ADD AC_UFIMOB DM_CHAR_UNIDADE;
ALTER TABLE AGENCIA ADD AC_CODCIDADEIMOB DM_INTEGER;
ALTER TABLE AGENCIA ADD AC_CIDADEIMOB DM_VARCHAR_NOME;
