ALTER TABLE CONTASRECEBER ADD CR_AGENCIA DM_INTEGER;
ALTER TABLE CONTASPAGAR ADD CG_AGENCIA DM_INTEGER;
ALTER TABLE CAIXA ADD CX_AGENCIA DM_INTEGER;

ALTER TABLE CORRETOR ADD CO_STATUS DM_CHAR_LOGICO COLLATE PXW_INTL850;
UPDATE CORRETOR SET CO_STATUS = 'A';

ALTER TABLE VENDALANCAMENTOS ADD VL_TIPO DM_CHAR_LOGICO COLLATE PXW_INTL850;
UPDATE VENDALANCAMENTOS SET VL_TIPO = 'C';

ALTER TABLE VENDALANCAMENTOS ADD VL_LANCAMENTOTIPO DM_CHAR_LOGICO COLLATE PXW_INTL850;
UPDATE VENDALANCAMENTOS SET VL_LANCAMENTOTIPO = 'C';
ALTER TABLE VENDALANCAMENTOS ADD VL_PREVISAO DM_DATE;

ALTER TABLE VENDALANCAMENTOS ADD VL_LANCAMENTO_DESC DM_VARCHAR_DESCRICAO COLLATE PXW_INTL850;
ALTER TABLE CONFIGURACOES_COBRANCA ADD CC_AGENCIA DM_INTEGER;

update RDB$RELATION_FIELDS set RDB$NULL_FLAG = NULL where (RDB$FIELD_NAME = 'CX_AGENCIA') and (RDB$RELATION_NAME = 'CAIXA');

ALTER TABLE CLIENTES ADD CL_INTERESSADOCADASTRADO DM_CHAR_LOGICO COLLATE PXW_INTL850;
ALTER TABLE CLIENTES ADD CL_INTERESSADOCODIGO DM_INTEGER;
UPDATE CLIENTES SET CL_INTERESSADOCADASTRADO = 'N';