update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_VARCHAR_NOME' where (RDB$FIELD_NAME = 'CL_PAI') and (RDB$RELATION_NAME = 'CLIENTES');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_VARCHAR_NOME' where (RDB$FIELD_NAME = 'CL_MAE') and (RDB$RELATION_NAME = 'CLIENTES');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_VARCHAR_NOME' where (RDB$FIELD_NAME = 'CL_CONJUGE') and (RDB$RELATION_NAME = 'CLIENTES');
update RDB$RELATION_FIELDS set RDB$FIELD_SOURCE = 'DM_VARCHAR_NOME' where (RDB$FIELD_NAME = 'CL_TITULARCONTA') and (RDB$RELATION_NAME = 'CLIENTES');