ALTER TABLE CONFIGURACOES_COBRANCA
ADD CC_PIX_SISTEMA_IDPK INTEGER,
ADD CC_PIX_EMPRESA_IDPK INTEGER,
ADD CC_PIX_FILIAL_IDPK INTEGER,
ADD CC_PIX_EMAIL VARCHAR(150),
ADD CC_PIX_SENHA VARCHAR(50),
ADD CC_PIX_TIPO_API INTEGER,
ADD CC_ENVIA_EMAIL_AUT VARCHAR(1);

ALTER TABLE CONFIGURACOES
ADD CF_PIX_SISTEMA_IDPK INTEGER,
ADD CF_PIX_EMPRESA_IDPK INTEGER,
ADD CF_PIX_FILIAL_IDPK INTEGER,
ADD CF_PIX_EMAIL VARCHAR(150),
ADD CF_PIX_SENHA VARCHAR(50),
ADD CF_PIX_TIPO_API INTEGER,
ADD CF_ENVIA_EMAIL_AUT VARCHAR(1);





