ALTER TABLE INTERESSADOS ADD IN_SITUACAO DM_CHAR_LOGICO DEFAULT 'A' COLLATE PXW_INTL850;

UPDATE INTERESSADOS SET IN_SITUACAO = 'A';

CREATE TABLE VEICULO (VI_CODIGO DM_INTEGER_PK, VI_NOME DM_VARCHAR_DESCRICAO COLLATE PXW_INTL850);

ALTER TABLE VEICULO ADD CONSTRAINT PK_VEICULO PRIMARY KEY (VI_CODIGO);

ALTER TABLE INTERESSADOS ADD IN_VEICULO DM_INTEGER;

alter table INTERESSADOS add constraint FK_INTERESSADOS_VEICULOS foreign key (IN_VEICULO) references VEICULO(VI_CODIGO) on update CASCADE;

CREATE TABLE INTERESSADOCORRETORES (IC_INTERESSADO DM_INTEGER_PK, IC_CORRETOR DM_INTEGER_PK);

ALTER TABLE INTERESSADOCORRETORES ADD CONSTRAINT PK_INTERESSADOCORRETORES PRIMARY KEY (IC_INTERESSADO, IC_CORRETOR);

ALTER TABLE INTERESSADOCORRETORES ADD CONSTRAINT FK_INTERESSADOCORRETORES_CORRET FOREIGN KEY (IC_CORRETOR) REFERENCES CORRETOR (CO_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INTERESSADOCORRETORES ADD CONSTRAINT FK_INTERESSADOCORRETORES_INTERE FOREIGN KEY (IC_INTERESSADO) REFERENCES INTERESSADOS (IN_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE USUARIO ADD US_CADVEICULOS DM_CHAR_LOGICO DEFAULT 'S' COLLATE PXW_INTL850;

UPDATE USUARIO SET US_CADVEICULOS = 'S';

CREATE TABLE TIPOCONTATO (TC_CODIGO DM_INTEGER_PK, TC_DESCRICAO DM_VARCHAR_MEDIO COLLATE PXW_INTL850);

ALTER TABLE TIPOCONTATO ADD CONSTRAINT PK_TIPOCONTATO PRIMARY KEY (TC_CODIGO);

ALTER TABLE USUARIO ADD US_CADTIPOCONTATO DM_CHAR_LOGICO DEFAULT 'S' COLLATE PXW_INTL850;

UPDATE USUARIO SET US_CADTIPOCONTATO = 'S';

CREATE TABLE ATENDIMENTOS (AT_CODIGO DM_INTEGER_PK, AT_INTERESSADO DM_INTEGER_PK, AT_DATA DM_DATE, AT_HORA DM_TIME, AT_DESCRICAO DM_VARCHAR_OBS_250 COLLATE PXW_INTL850, AT_TIPOCONTATO DM_INTEGER);

ALTER TABLE ATENDIMENTOS ADD CONSTRAINT PK_ATENDIMENTOS PRIMARY KEY (AT_INTERESSADO, AT_CODIGO);

ALTER TABLE ATENDIMENTOS ADD CONSTRAINT FK_ATENDIMENTOS_TIPOCONTATO FOREIGN KEY (AT_TIPOCONTATO) REFERENCES TIPOCONTATO (TC_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

alter table ATENDIMENTOS add constraint FK_ATENDIMENTOS_INTERESSADO foreign key (AT_INTERESSADO) references INTERESSADOS(IN_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INTERESSADOS ADD IN_ATENDIMENTOAGENDADO DM_CHAR_LOGICO COLLATE PXW_INTL850;

ALTER TABLE INTERESSADOS ADD IN_ATENDIMENTODATA DM_DATE;

ALTER TABLE INTERESSADOS ADD IN_ATENDIMENTOHORA DM_TIME;

ALTER TABLE INTERESSADOS ADD IN_ATENDIMENTODESCRICAO DM_VARCHAR_MEDIO COLLATE PXW_INTL850;

ALTER TABLE CONFIGURACOES ADD CF_ATENDDIAS DM_INTEGER;

UPDATE CONFIGURACOES SET CF_ATENDDIAS = '5';

ALTER TABLE CONFIGURACOES ADD CF_ATENDDESCRICAO DM_VARCHAR_MEDIO COLLATE PXW_INTL850;

UPDATE CONFIGURACOES SET CF_ATENDDESCRICAO = 'Continuar atendimento';

ALTER TABLE ATENDIMENTOS ADD AT_IMOVEL DM_INTEGER;

CREATE TABLE INTERESSADOIMOVEIS (II_INTERESSADO DM_INTEGER_PK, II_IMOVEL DM_INTEGER_PK);

ALTER TABLE INTERESSADOIMOVEIS ADD CONSTRAINT PK_INTERESSADOIMOVEIS PRIMARY KEY (II_INTERESSADO, II_IMOVEL);

ALTER TABLE INTERESSADOIMOVEIS ADD CONSTRAINT FK_INTERESSADOIMOVEIS_IMOVEIS FOREIGN KEY (II_IMOVEL) REFERENCES IMOVEIS (IM_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE INTERESSADOIMOVEIS ADD CONSTRAINT FK_INTERESSADOIMOVEIS_INTERESSA FOREIGN KEY (II_INTERESSADO) REFERENCES INTERESSADOS (IN_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

