CREATE TABLE IMOVEISDOCUMENTOS (ID_CODIGO DM_INTEGER_PK, ID_IMOVEL DM_INTEGER_PK, ID_DOCUMENTO DM_VARCHAR_OBS_250 COLLATE PXW_INTL850);

ALTER TABLE IMOVEISDOCUMENTOS ADD CONSTRAINT PK_IMOVEISDOCUMENTOS PRIMARY KEY (ID_CODIGO);

ALTER TABLE IMOVEISDOCUMENTOS ADD CONSTRAINT FK_IMOVEISDOCUMENTOS_IMOVEL FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEIS (IM_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE IMOVEISVIDEOS (IV_CODIGO  DM_INTEGER_PK, IV_IMOVEL DM_INTEGER_PK, IV_VIDEO DM_VARCHAR_OBS_250 COLLATE PXW_INTL850);

ALTER TABLE IMOVEISVIDEOS ADD CONSTRAINT PK_IMOVEISVIDEOS PRIMARY KEY (IV_CODIGO);

ALTER TABLE IMOVEISVIDEOS ADD CONSTRAINT FK_IMOVEISVIDEOS_IMOVEL FOREIGN KEY (IV_IMOVEL) REFERENCES IMOVEIS (IM_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;
