CREATE TABLE NFSEEMAIL (
    NE_NFSECODIGO  DM_INTEGER,
    NE_DATAHORA    DM_VARCHAR_MEDIO,
    NE_EMAIL       DM_VARCHAR_DESCRICAO);
ALTER TABLE NFSEEMAIL ADD CONSTRAINT FK_NFSEEMAIL_1 FOREIGN KEY (NE_NFSECODIGO) REFERENCES NFSE (NF_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;