ALTER TABLE INTERESSADOS ADD IN_TIPO_RR DM_CHAR_LOGICO;
ALTER TABLE INTERESSADOS ADD IN_EXCLUIDO DM_CHAR_LOGICO DEFAULT 'N';
ALTER TABLE INTERESSADOS ADD IN_EXCLUSAOMOTIVO DM_VARCHAR_MEDIO;
ALTER TABLE INTERESSADOS ADD IN_EXCLUSAOUSUARIO DM_VARCHAR_MEDIO;
ALTER TABLE INTERESSADOS ADD IN_EXCLUSAODATA DM_DATE;
update interessados set in_excluido = 'N';
ALTER TABLE IMOVEIS ADD IM_SITEOCULTARAREA DM_CHAR_LOGICO DEFAULT 'N';
update IMOVEIS set IM_SITEOCULTARAREA = 'N';
