CREATE TABLE NFSESERVICO (
    NS_CODIGO     DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    NS_DESCRICAO  DM_VARCHAR_NOME /* DM_VARCHAR_NOME = VARCHAR(51) CHECK (VALUE<>'') */
);
ALTER TABLE NFSESERVICO ADD CONSTRAINT PK_NFSESERVICO PRIMARY KEY (NS_CODIGO);