CREATE TABLE CLIFORMAPAG (
    CF_CLIENTE  DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    CF_CODIGO   DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    CF_FIXO     DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */,
    CF_MESINI   DM_CHAR_MES COLLATE PXW_INTL850 /* DM_CHAR_MES = CHAR(5) */,
    CF_MESFIM   DM_CHAR_MES COLLATE PXW_INTL850 /* DM_CHAR_MES = CHAR(5) */,
    CF_DATAINI  DM_DATE /* DM_DATE = DATE */,
    CF_DATAFIM  DM_DATE /* DM_DATE = DATE */
);

ALTER TABLE CLIFORMAPAG ADD CONSTRAINT PK_CLIFORMAPAG PRIMARY KEY (CF_CLIENTE, CF_CODIGO);

ALTER TABLE CLIFORMAPAG ADD CONSTRAINT FK_CLIFORMAPAG_CLIENTE FOREIGN KEY (CF_CLIENTE) REFERENCES CLIENTES (CL_CODIGO) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE CLIFORMAPAGCONTA (
    CFC_CLIENTEFORMAPAG  DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    CFC_CODIGOFORMAPAG   DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    CFC_SEQUENCIAL       DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    CFC_TIPOPAG          DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */,
    CFC_BANCO            DM_INTEGER /* DM_INTEGER = INTEGER */,
    CFC_AGENCIA          DM_VARCHAR_10 COLLATE PXW_INTL850 /* DM_VARCHAR_10 = VARCHAR(10) */,
    CFC_CONTA            DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */,
    CFC_TIPOCONTA        DM_CHAR_LOGICO COLLATE PXW_INTL850 /* DM_CHAR_LOGICO = CHAR(1) */,
    CFC_PERCENTUAL       DM_DINHEIRO /* DM_DINHEIRO = DECIMAL(15,2) */,
    CFC_TITULAR          DM_VARCHAR_MEDIO COLLATE PXW_INTL850 /* DM_VARCHAR_MEDIO = VARCHAR(30) */
);

ALTER TABLE CLIFORMAPAGCONTA ADD CONSTRAINT PK_CLIFORMAPAGCONTA PRIMARY KEY (CFC_CLIENTEFORMAPAG, CFC_CODIGOFORMAPAG, CFC_SEQUENCIAL);

ALTER TABLE CLIFORMAPAGCONTA ADD CONSTRAINT FK_CLIFORMAPAGCONTA_BANCO FOREIGN KEY (CFC_BANCO) REFERENCES BANCOS (BN_CODIGO) ON UPDATE CASCADE;

ALTER TABLE CLIENTES ADD CL_CONTATIPO DM_CHAR_LOGICO COLLATE PXW_INTL850;