ALTER TABLE NFSECONFIGURACAO ADD NC_PROXIMOLOTE DM_INTEGER;
ALTER TABLE NFSECONFIGURACAO ADD NC_PROXIMORPS DM_INTEGER;
UPDATE NFSECONFIGURACAO SET NC_PROXIMOLOTE = 1;
UPDATE NFSECONFIGURACAO SET NC_PROXIMORPS = 1;
