CREATE TABLE NFSE_ITEM (
    NFI_NFSECODIGO     DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    NFI_ITEM           DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    NFI_SERVICO        DM_INTEGER_PK /* DM_INTEGER_PK = INTEGER NOT NULL CHECK (VALUE > 0) */,
    NFI_COMPLEMENTO    DM_VARCHAR_DESCRICAO /* DM_VARCHAR_DESCRICAO = VARCHAR(100) */,
    NFI_QUANTIDADE     DM_DINHEIRO /* DM_DINHEIRO = DECIMAL(15,2) */,
    NFI_VALORUNITARIO  DM_DINHEIRO /* DM_DINHEIRO = DECIMAL(15,2) */,
    NFI_VALORTOTAL     DM_DINHEIRO /* DM_DINHEIRO = DECIMAL(15,2) */
);

ALTER TABLE NFSE_ITEM ADD CONSTRAINT PK_NFSE_ITEM PRIMARY KEY (NFI_NFSECODIGO, NFI_ITEM);

ALTER TABLE NFSE_ITEM ADD CONSTRAINT FK_NFSE_ITEM_SERVICO FOREIGN KEY (NFI_SERVICO) REFERENCES NFSESERVICO (NS_CODIGO) ON UPDATE CASCADE;
