ALTER TABLE CUPOM_TEF
ADD DESCRICAO VARCHAR(20);

ALTER TABLE CUPOM_PIXAPAY
ADD DESCRICAO VARCHAR(20);

ALTER TABLE CUPOM_TEF
ADD COMPROVANTE_ESTAB BLOB SUB_TYPE 1 SEGMENT SIZE 16384;

ALTER TABLE CUPOM_TEF
ADD COMPROVANTE_CLI BLOB SUB_TYPE 1 SEGMENT SIZE 16384;

ALTER TABLE CUPOM_TEF
ADD CONDICAO_PAGAMENTO VARCHAR(10);

ALTER TABLE CUPOM_TEF
ADD MOTIVO_ERRO VARCHAR(100);







