CREATE TABLE CONFIG_PIXAPAY (
    CODIGO                 INTEGER NOT NULL,
    FINANCEIRO_CONTA_IDPK  INTEGER,
    SISTEMA_IDPK           INTEGER,
    EMPRESA_IDPK           INTEGER,
    FILIAL_IDPK            INTEGER,
    USERNAME               VARCHAR(50),
    "PASSWORD"             VARCHAR(50),
    IMPRIMIR_QRCODE        CHAR(1),
    BASE_URL               VARCHAR(150)
);

ALTER TABLE CONFIG_PIXAPAY ADD CONSTRAINT PK_CONFIG_PIXAPAY PRIMARY KEY (CODIGO);