update RDB$FIELDS set
RDB$FIELD_LENGTH = 100,
RDB$CHARACTER_LENGTH = 100
where RDB$FIELD_NAME = 'RDB$1699'
;

update RDB$FIELDS set
RDB$FIELD_LENGTH = 100,
RDB$CHARACTER_LENGTH = 100
where RDB$FIELD_NAME = 'RDB$1698'
;

update RDB$FIELDS set
RDB$FIELD_LENGTH = 200,
RDB$CHARACTER_LENGTH = 200
where RDB$FIELD_NAME = 'RDB$1708'
;

update RDB$FIELDS set
RDB$FIELD_LENGTH = 200,
RDB$CHARACTER_LENGTH = 200
where RDB$FIELD_NAME = 'RDB$1706'
;

