ALTER TABLE CONFIG ADD SEQ_NFCE INTEGER;
ALTER TABLE CONFIG ADD SEQ_NFCE_NAOFISCAL INTEGER;
UPDATE CONFIG SET SEQ_NFCE = 1;
UPDATE CONFIG SET SEQ_NFCE_NAOFISCAL = 1;
CREATE TABLE EMITE_CONTIGENCIA (
    CODIGO           INTEGER,
    ITEM             INTEGER,
    COD_PRODUTO      INTEGER,
    UNIDADE          VARCHAR(5),
    QTDE             NUMERIC(15,4),
    VALOR_UNITARIO   NUMERIC(15,3),
    VALOR_SUBTOTAL   NUMERIC(15,2),
    VALOR_DESCONTO   NUMERIC(15,2),
    VALOR_ACRESCIMO  NUMERIC(15,2),
    VALOR_TOTAL      NUMERIC(15,2),
    CST              VARCHAR(3),
    ALIQUOTA         NUMERIC(15,2),
    COD_TOTALIZADOR  VARCHAR(7),
    CANCELADO        INTEGER,
    DESCRICAO        VARCHAR(40),
    FORMA_PAGAMENTO  VARCHAR(30),
    VALOR_PAGO       NUMERIC(15,2)
);
CREATE TABLE EMITENTE (
    CODIGO                 VARCHAR(6) NOT NULL,
    NOME                   VARCHAR(80),
    FANTASIA               VARCHAR(80),
    ENDERECO               VARCHAR(80),
    BAIRRO                 VARCHAR(30),
    CIDADE                 VARCHAR(40),
    UF                     VARCHAR(2),
    CEP                    VARCHAR(10),
    TELEFONE               VARCHAR(20),
    CNPJ                   VARCHAR(25),
    IE                     VARCHAR(20),
    EMAIL                  VARCHAR(80),
    HOMEPAGE               VARCHAR(80),
    RESPONSAVEL            VARCHAR(50),
    CELULAR                VARCHAR(20),
    LOGO                   BLOB SUB_TYPE 0 SEGMENT SIZE 80,
    FAX                    VARCHAR(20),
    NUMERO                 VARCHAR(10),
    COMPLEMENTO            VARCHAR(30),
    CONTRIBUINTE_IPI       VARCHAR(4),
    SUBSTITUTO_TRIBUTARIO  VARCHAR(4),
    COMENTARIOS            VARCHAR(50),
    DATAHORA_INICIAL       DATE,
    DATAHORA_FINAL         DATE,
    DATA_INVENTARIO        DATE,
    ESTOQUE                NUMERIC(15,2),
    VALOR                  NUMERIC(15,2),
    CONHECIMENTO           INTEGER,
    CPF                    VARCHAR(20),
    RG                     VARCHAR(20),
    DIA_VENCIMENTO_CHAVE   VARCHAR(2),
    INSC_MUNICIPAL         VARCHAR(20),
    DATA_ABERTURA          DATE,
    COD_MUNICIPIO_IBGE     VARCHAR(10),
    IBGE                   VARCHAR(10)
);
ALTER TABLE ESTOQUE ADD NCM VARCHAR(20);
ALTER TABLE CLIENTE ADD NUMERO VARCHAR(10);
ALTER TABLE CLIENTE ADD COD_MUNICIPIO_IBGE VARCHAR(10);
ALTER TABLE CLIENTE ADD TELEFONE1 VARCHAR(20);