CREATE TABLE FORMAS_PAGAMENTO (
	IDPK INTEGER NOT NULL,
	TIPO VARCHAR(100),
	FORMA VARCHAR(100),
	ATIVO SMALLINT
);

INSERT INTO FORMAS_PAGAMENTO (IDPK,TIPO,FORMA,ATIVO) VALUES (1,'DINHEIRO','Vista',1);
INSERT INTO FORMAS_PAGAMENTO (IDPK,TIPO,FORMA,ATIVO) VALUES (2,'PIX','Pix',1);
INSERT INTO FORMAS_PAGAMENTO (IDPK,TIPO,FORMA,ATIVO) VALUES (3,'CREDIARIO','Prazo',1);
INSERT INTO FORMAS_PAGAMENTO (IDPK,TIPO,FORMA,ATIVO) VALUES (4,'CONVENIO','Convênio',1);
INSERT INTO FORMAS_PAGAMENTO (IDPK,TIPO,FORMA,ATIVO) VALUES (5,'CHEQUE','Cheque',1);
INSERT INTO FORMAS_PAGAMENTO (IDPK,TIPO,FORMA,ATIVO) VALUES (6,'CARTAO_DEBITO','Débito',1);
INSERT INTO FORMAS_PAGAMENTO (IDPK,TIPO,FORMA,ATIVO) VALUES (7,'CARTAO_CREDITO','Crédito',1);


