ALTER TABLE NFCE ADD NFE_CARTA_DATAHORA      VARCHAR(30);
ALTER TABLE NFCE ADD NFE_CARTA_PROTOCOLO     VARCHAR(100);
ALTER TABLE NFCE ADD NFE_CARTA_XML           VARCHAR(240);
ALTER TABLE NFCE ADD NFE_CARTA_CODIGOSTATUS  VARCHAR(10);
ALTER TABLE NFCE ADD NFE_CARTA_MOTIVOSTATUS  VARCHAR(40);
ALTER TABLE NFCE ADD NFE_CARTA_SEQUENCIAL    INTEGER;
ALTER TABLE NFCE ADD NFE_CARTA_TEXTO         VARCHAR(250);