ALTER TABLE CONFIG_PDV
ADD CNPJ_CREDENCIADORA_TEF VARCHAR(20);

ALTER TABLE CONFIG_PDV
ADD IMPRIME_APENAS_VIA_CLIENTE_TEF SMALLINT;


CREATE GENERATOR GEN_CUPOM_TEF_ID;

CREATE TABLE CUPOM_TEF (
    ID                   INTEGER NOT NULL,
    COD_AUTORIZACAO      VARCHAR(50),
    NSU                  VARCHAR(50),
    VALOR                FLOAT,
    BANDEIRA             VARCHAR(50),
    REDE                 VARCHAR(50),
    NUMERO_CUPOM         VARCHAR(50),
    DATA_HORA_TRANSACAO  TIMESTAMP
);

ALTER TABLE CUPOM_TEF ADD CONSTRAINT PK_CUPOM_TEF PRIMARY KEY (ID);

SET TERM ^ ;

CREATE OR ALTER TRIGGER CUPOM_TEF_BI FOR CUPOM_TEF
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_cupom_tef_id,1);
end
^

SET TERM ; ^