ALTER TABLE CONFIG_PIXAPAY ADD LARGURA_QRCODE INTEGER;
UPDATE CONFIG_PIXAPAY SET LARGURA_QRCODE = 300;

ALTER TABLE CUPOM_ITEM ALTER COR TYPE VARCHAR(15);
ALTER TABLE CUPOM_ITEM ALTER TAMANHO TYPE VARCHAR(10);

ALTER TABLE CUPOM_ITEM_TEMP ALTER COR TYPE VARCHAR(15);
ALTER TABLE CUPOM_ITEM_TEMP ALTER TAMANHO TYPE VARCHAR(10);