ALTER TABLE CONFIG_PDV
ADD ACRESCIMO_FIXO SMALLINT;

ALTER TABLE CONFIG_PDV
ADD ACRESCIMO_FIXO_VALOR FLOAT;

ALTER TABLE CONFIG_PDV
ADD ACRESCIMO_FIXO_TIPO SMALLINT;

UPDATE CONFIG_PDV SET ACRESCIMO_FIXO = 0;
UPDATE CONFIG_PDV SET ACRESCIMO_FIXO_VALOR = 0;
UPDATE CONFIG_PDV SET ACRESCIMO_FIXO_TIPO = 0;