CREATE TABLE IND_MIST_BIODIESEL (
    CODIGO INTEGER,
    COD_PRODUTO VARCHAR(6),
    INDICADOR_IMPORTACAO INTEGER,
    COD_UF_ORIGEM INTEGER,
    PERCENTUAL_ORIGINARIO_UF FLOAT);

ALTER TABLE ESTOQUE
ADD PERC_MISTURA_BIODIESEL NUMERIC(15,2);