ALTER TABLE CONFIG ADD IMPRIME_RECIBO_CONTASRECEBER INTEGER DEFAULT 0 ;

COMMENT ON COLUMN CONFIG.IMPRIME_RECIBO_CONTASRECEBER IS '0 = RESUMIDO / 1 = DETALHADO';

update config set IMPRIME_RECIBO_CONTASRECEBER = 0;





 
