CREATE GENERATOR PIX_ID;

CREATE TABLE CUPOM_PIXAPAY (
    FMP_IDPK                     INTEGER,
    FMP_STATUS                   VARCHAR(50),
    FMP_PAGADOR_NOME             VARCHAR(50),
    FMP_PAGADOR_BANCO            VARCHAR(50),
    FMP_PAGADOR_CONTA            VARCHAR(50),
    FMP_PAGAMENTO_DATA           VARCHAR(20),
    FMP_PAGADOR_AGENCIA          VARCHAR(10),
    FMP_PAGADOR_DOCUMENTO        VARCHAR(50),
    FMP_PAGADOR_CONTA_TIPO       VARCHAR(10),
    FMP_COBRANCA_VALOR_RECEBIDO  DECIMAL(18,2),
    FMP_PAGAMENTO_TRANSACAO_ID   VARCHAR(100),
    NUMERO_CUPOM                 VARCHAR(50),
    SINCRONIZADO                 INTEGER,
    ID                           INTEGER NOT NULL,
    COD_CUPOM                    VARCHAR(80)
);

ALTER TABLE CUPOM_PIXAPAY ADD CONSTRAINT PIX_ID PRIMARY KEY (ID);

SET TERM ^ ;

CREATE OR ALTER TRIGGER PIXAPAY_AUTOINCREMENT FOR CUPOM_PIXAPAY
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    NEW.ID = NEXT VALUE FOR PIX_ID;
END^

SET TERM ; ^

ALTER TABLE CONFIG
ADD FORMA_PIX VARCHAR(50)

