ALTER TABLE CONFIG DROP TOTALIZADOR_NF_CREDIARIO;
ALTER TABLE CONFIG DROP NOME_TOTALIZADOR_NF_CREDIARIO;
ALTER TABLE CONFIG DROP TOTALIZADOR_NF_RECEBIMENTO;
ALTER TABLE CONFIG DROP NOME_TOTALIZADOR_NF_RECEBIMENTO;
ALTER TABLE CONFIG DROP TOTALIZADOR_SANGRIA;
ALTER TABLE CONFIG DROP TOTALIZADOR_SUPRIMENTO;

ALTER TABLE EMITENTE ADD CRT SMALLINT;