CREATE TABLE CONFIG_PDV (
	ID INTEGER,
	TEF_PAYGO SMALLINT,
	TEF_TECBAN SMALLINT,
	TEF_HIPERCARD SMALLINT,
	ALTERAR_UNITARIO SMALLINT,
	ALTERAR_QUANTIDADE SMALLINT,
	ALTERAR_TOTAL SMALLINT,
	COLUNA_CONSULTA_PRODUTOS SMALLINT,
	INFORMAR_VENDEDOR_FIM SMALLINT,
	INFORMAR_CONSUMIDOR_INICIO SMALLINT,
	OCULTAR_ACRESCIMO SMALLINT,
	PRECO_PRODUTO SMALLINT,
	RAMO_ATIVIDADE SMALLINT,
	DESCONTO_PADRAO SMALLINT,
	VALOR_UNITARIO SMALLINT,
	ENVIAR_AUTO_NFCE SMALLINT,
	AJUSTAR_RESOLUCAO SMALLINT,
	IMPRIMIR_CARNE SMALLINT,
	IMPRIMIR_COMPROVANTE_CREDI SMALLINT,
	IMPRIMIR_PROD_COMPROVANTE SMALLINT,
	IMPRIMIR_RECIBO_RECEBER SMALLINT,
	MENSAGEM_RODAPE VARCHAR(500),
	PERMITIR_PROD_SEM_ESTOQUE SMALLINT,
	AVISAR_PROD_SEM_ESTOQUE SMALLINT,
	PESQUISAR_PROD_PESAVEIS SMALLINT,
	PEDIR_SENHA_ABRIR_GAVETA SMALLINT,
	IMPRIMIR_CODIGO_BARRAS SMALLINT,
	IMPRIMIR_SEGUNDA_VIA SMALLINT,
	IMPRIMIR_SALDO_DISPONIVEL SMALLINT,
	IMPRIMIR_COMPROVANTE_ESPAC SMALLINT,
	IMPRIMIR_AUTO_ENVIO SMALLINT,
	ALTERAR_UNITARIO_PROD_PROMO SMALLINT,
	PRECO_PROMOCIONAL SMALLINT,
	POSTO_QTDE_CASAS_DECIMAIS SMALLINT
);

INSERT INTO CONFIG_PDV 
(ID,TEF_PAYGO,TEF_TECBAN,TEF_HIPERCARD,ALTERAR_UNITARIO,ALTERAR_QUANTIDADE,ALTERAR_TOTAL,COLUNA_CONSULTA_PRODUTOS,INFORMAR_VENDEDOR_FIM,INFORMAR_CONSUMIDOR_INICIO,OCULTAR_ACRESCIMO,PRECO_PRODUTO,RAMO_ATIVIDADE,DESCONTO_PADRAO,VALOR_UNITARIO,ENVIAR_AUTO_NFCE,AJUSTAR_RESOLUCAO,IMPRIMIR_CARNE,IMPRIMIR_COMPROVANTE_CREDI,IMPRIMIR_PROD_COMPROVANTE,IMPRIMIR_RECIBO_RECEBER,MENSAGEM_RODAPE,PERMITIR_PROD_SEM_ESTOQUE,AVISAR_PROD_SEM_ESTOQUE,PESQUISAR_PROD_PESAVEIS,PEDIR_SENHA_ABRIR_GAVETA,IMPRIMIR_CODIGO_BARRAS,IMPRIMIR_SEGUNDA_VIA,IMPRIMIR_SALDO_DISPONIVEL,IMPRIMIR_COMPROVANTE_ESPAC,IMPRIMIR_AUTO_ENVIO,ALTERAR_UNITARIO_PROD_PROMO,PRECO_PROMOCIONAL,POSTO_QTDE_CASAS_DECIMAIS) 
VALUES
(1,0,0,0,0,0,0,0,0,0,NULL,0,0,0,0,0,0,0,0,0,0,'Volte Sempre!',1,0,0,0,0,0,0,0,0,0,0,0);
