ALTER TABLE CLIENTE ADD CARRO_KILOMETRAGEM VARCHAR(10);
ALTER TABLE CLIENTE ADD CARRO_PLACA VARCHAR(10);
CREATE TABLE VEICULOS (CODIGO VARCHAR(6) NOT NULL, CODCLIENTE VARCHAR(6), VEICULO VARCHAR(30), PLACA VARCHAR(8), UF VARCHAR(2), ANO VARCHAR(10), COMBUSTIVEL VARCHAR(15), RENAVAM VARCHAR(30), DATA DATE, OBS1 VARCHAR(80), OBS2 VARCHAR(80), OBS3 VARCHAR(80), COR VARCHAR(10), CHASSI VARCHAR(40));
ALTER TABLE VEICULOS ADD CONSTRAINT PK_VEICULOS PRIMARY KEY (CODIGO);
ALTER TABLE VEICULOS ADD EX INTEGER DEFAULT 0 NOT NULL ;





