CREATE TABLE VARIACAO_PRECO_VENDA (
    CODIGO     VARCHAR(10) NOT NULL,
    NOME       VARCHAR(30),
    ACRESCIMO  FLOAT,
    DESCONTO   FLOAT,
    DATA       TIMESTAMP
);


ALTER TABLE VARIACAO_PRECO_VENDA ADD CONSTRAINT PK_VARIACAO_PRECO_VENDA PRIMARY KEY (CODIGO);

ALTER TABLE ESTOQUE
ADD VARIACAO_PRECO_VENDA VARCHAR(10);


