ALTER TABLE CONFIG_PDV
ADD POS_PAGBANK SMALLINT;

ALTER TABLE CONFIG_PDV
ADD POS_EMAIL VARCHAR(50);

ALTER TABLE CONFIG_PDV
ADD POS_SENHA VARCHAR(50);

ALTER TABLE CUPOM_TEF
ADD TIPO_MAQUININHA VARCHAR(3);

ALTER TABLE CONFIG_PDV
ADD VIAS_IMPRESSAO INTEGER;

UPDATE CONFIG_PDV SET VIAS_IMPRESSAO = 1;

UPDATE CUPOM_TEF SET TIPO_MAQUININHA = 'TEF';


