ALTER TABLE CUPOM_TEF
ADD CONTA_RECEBIMENTO VARCHAR(150);

ALTER TABLE CUPOM_TEF
ADD CHAVE_NFCE_RECEBIMENTO VARCHAR(50);

ALTER TABLE CUPOM_PIXAPAY
ADD CONTA_RECEBIMENTO VARCHAR(150);

ALTER TABLE CUPOM_PIXAPAY
ADD CHAVE_NFCE_RECEBIMENTO VARCHAR(50);

ALTER TABLE CUPOM_TEF
ADD NFCE_XML_RECEBIMENTO VARCHAR(240);

ALTER TABLE CUPOM_PIXAPAY
ADD NFCE_XML_RECEBIMENTO VARCHAR(240);







