ALTER TABLE ESTOQUE ADD IMPOSTOCA_VBCSTRET NUMERIC(15,2);
ALTER TABLE ESTOQUE ADD IMPOSTOCA_VICMSSTRET NUMERIC(15,2);
ALTER TABLE ESTOQUE ADD IMPOSTOCA_PST NUMERIC(15,2);
UPDATE ESTOQUE SET IMPOSTOCA_VBCSTRET = 0;
UPDATE ESTOQUE SET IMPOSTOCA_VICMSSTRET = 0;
UPDATE ESTOQUE SET IMPOSTOCA_PST = 0;