alter table NFCEITENS add is_cst VARCHAR(3);
alter table NFCEITENS add is_cclasstrib VARCHAR(6);
alter table NFCEITENS add is_vbc NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add is_p NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add is_pespec NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add is_utrib VARCHAR(6);
alter table NFCEITENS add is_qtrib NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add is_v NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add ibscbs_cst VARCHAR(3);
alter table NFCEITENS add ibscbs_cclasstrib VARCHAR(6);
alter table NFCEITENS add ibscbs_inddoacao INTEGER;
alter table NFCEITENS add ibscbs_vbc NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add ibs_v NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add ibs_uf_p NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add ibs_uf_pdif NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add ibs_uf_vdif NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add ibs_uf_vdevtrib NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add ibs_uf_predaliq NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add ibs_uf_paliqefet NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add ibs_uf_v NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add ibs_mun_p NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add ibs_mun_pdif NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add ibs_mun_vdif NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add ibs_mun_vdevtrib NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add ibs_mun_predaliq NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add ibs_mun_paliqefet NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add ibs_mun_v NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add cbs_p NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add cbs_pdif NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add cbs_vdif NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add cbs_vdevtrib NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add cbs_predaliq NUMERIC(15,4) DEFAULT 0.0;
alter table NFCEITENS add cbs_paliqefet NUMERIC(15,2) DEFAULT 0.0;
alter table NFCEITENS add cbs_v NUMERIC(15,2) DEFAULT 0.0;