/*DOUGLAS - CRIANDO ESTRUTURA PARA TABELA DE PREÇOS DIFERENCIADOS IGUAL AO BASE.FDB (ALTERADO PARA POSTO JOÃOZINHO ACCO)*/
CREATE TABLE PRODUTO_TABELA (CODIGO VARCHAR(6) NOT NULL, CODPRODUTO VARCHAR(6) NOT NULL, CODTABELA VARCHAR(6) NOT NULL, PRECO NUMERIC(15,2) NOT NULL);
alter table PRODUTO_TABELA add constraint PK_PRODUTO_TABELA primary key (CODIGO);

CREATE TABLE TABELA_PRECOS (CODIGO VARCHAR(6) NOT NULL, DESCRICAO VARCHAR(30) NOT NULL, PERCENTUAL NUMERIC(15,3) NOT NULL);
alter table TABELA_PRECOS add constraint PK_TABELA_PRECOS primary key (CODIGO);

CREATE TABLE GRUPO_REGIAO (CODIGO VARCHAR(6) NOT NULL, REGIAO VARCHAR(30) NOT NULL, USARTABELA_PRECO INTEGER, CODTABELA_PRECO VARCHAR(6));
alter table GRUPO_REGIAO add constraint PK_GRUPO_REGIAO primary key (CODIGO);

ALTER TABLE CLIENTE ADD CODTABELA_PRECO VARCHAR(6);
ALTER TABLE CLIENTE ADD CODREGIAO VARCHAR(6);

/*DOUGLAS - DATAS PARA SINCRONIZAÇÃO DOS DADOS DOS GRUPOS, SOMENTE O QUE AINDA NÃO FOI SINCRONIZADO*/
ALTER TABLE CONFIG ADD PRODUTO_TABELA_ULTALT VARCHAR(28);
UPDATE CONFIG SET PRODUTO_TABELA_ULTALT = '01/01/2000 00:01:00' WHERE PRODUTO_TABELA_ULTALT IS NULL;
ALTER TABLE CONFIG ADD TABELA_PRECOS_ULTALT VARCHAR(28);
UPDATE CONFIG SET TABELA_PRECOS_ULTALT = '01/01/2000 00:01:00' WHERE TABELA_PRECOS_ULTALT IS NULL;
ALTER TABLE CONFIG ADD GRUPO_REGIAO_ULTALT VARCHAR(28);
UPDATE CONFIG SET GRUPO_REGIAO_ULTALT = '01/01/2000 00:01:00' WHERE GRUPO_REGIAO_ULTALT IS NULL;
