ALTER TABLE CONFIG ADD UNITARIO_PRODUTO_PROMOCAO VARCHAR(1);
UPDATE CONFIG SET UNITARIO_PRODUTO_PROMOCAO = '0';

ALTER TABLE CONFIG ADD AVISAR_ESTOQUE_INSUFICIENTE VARCHAR(1);
UPDATE CONFIG SET AVISAR_ESTOQUE_INSUFICIENTE = '0';
